#!/usr/bin/env bash
# swarmbotix sb CLI installer.
#
# Layout: this script ships INSIDE swarmbotix-<version>-<arch>.zip, at the top
# of the package beside bin/, messages/ and documents/. Unzip the package and
# run the install.sh that comes out of it: the payload is its own siblings,
# which it copies into $SB_HOME (default: ~/.swarmbotix). Nothing is
# downloaded and nothing is extracted here.
#
# Usage:
#   ./install.sh                 interactive (prompts before editing ~/.bashrc)
#   ./install.sh --yes           non-interactive; auto-accept bashrc edit
#   SB_HOME=/opt/sb ./install.sh custom install prefix (skips bashrc prompt)

set -euo pipefail

YES=0
for arg in "$@"; do
    case "$arg" in
        --yes|-y) YES=1 ;;
        --help|-h)
            sed -n '2,14p' "$0" | sed 's/^# \{0,1\}//'
            exit 0 ;;
        *) echo "unknown argument: $arg" >&2; exit 2 ;;
    esac
done

SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
SB_HOME="${SB_HOME:-$HOME/.swarmbotix}"
USING_DEFAULT_HOME=1
[[ "$SB_HOME" != "$HOME/.swarmbotix" ]] && USING_DEFAULT_HOME=0

# The payload is whatever was unzipped around this script, so there is no zip
# to find, nothing to extract and no temp dir to clean up. Assert the shape
# before touching $SB_HOME: a bare install.sh copied out of the package on its
# own would otherwise fail halfway through, with the home directory already
# half-written.
PAYLOAD_DIR="$SCRIPT_DIR"
if [[ ! -f "$PAYLOAD_DIR/bin/sb" || ! -d "$PAYLOAD_DIR/documents" ]]; then
    echo "error: install.sh is not sitting in an unpacked swarmbotix package." >&2
    echo "       Expected bin/sb and documents/ beside it, in ${SCRIPT_DIR}." >&2
    echo "       Unzip swarmbotix-<version>-<arch>.zip and run the install.sh inside it." >&2
    exit 1
fi

# Unpacking the package INTO $SB_HOME is a new way to get this wrong now that
# the user does the unzipping: source and destination would be the same tree,
# and the wholesale `rm -rf "$SB_HOME/documents"` below would delete the very
# files it is about to copy. Refuse instead of half-destroying it. `readlink -m`
# canonicalizes a path that does not exist yet, which $SB_HOME usually is.
SB_HOME_ABS="$(readlink -m "$SB_HOME")"
case "$PAYLOAD_DIR/" in
    "$SB_HOME_ABS"/*)
        echo "error: the package is unpacked inside \$SB_HOME (${SB_HOME_ABS})." >&2
        echo "       Installing from there would overwrite the payload as it copies." >&2
        echo "       Unzip somewhere else (e.g. ~/Downloads) and run that install.sh." >&2
        exit 1 ;;
esac

# One package per architecture, so this is an ASSERTION rather than a choice:
# the installer no longer picks between zips, it verifies the one it came out
# of. Installing an aarch64 payload on x86_64 would succeed here and then fail
# with "cannot execute binary file" on the first `sb`, long after the cause.
case "$(uname -m)" in
    x86_64|amd64)   HOST_ARCH=linux-x86_64 ;;
    aarch64|arm64)  HOST_ARCH=linux-aarch64 ;;
    *)
        echo "error: no swarmbotix build for this machine ($(uname -m))." >&2
        echo "       Supported: x86_64, aarch64." >&2
        exit 1 ;;
esac

# `platform:` in the staged VERSION file is the package's own arch, written by
# build.sh. Absent or unreadable is not fatal — a hand-assembled tree is still
# installable — but a value that DISAGREES is.
PKG_ARCH="$(awk '$1 == "platform:" { print $2 }' "$PAYLOAD_DIR/VERSION" 2>/dev/null || true)"
if [[ -n "$PKG_ARCH" && "$PKG_ARCH" != "$HOST_ARCH" ]]; then
    echo "error: this is the ${PKG_ARCH} package, but this machine is $(uname -m) (${HOST_ARCH})." >&2
    echo "       Download swarmbotix-<version>-${HOST_ARCH}.zip instead." >&2
    exit 1
fi

echo "Installing $(basename "$PAYLOAD_DIR") → $SB_HOME"

mkdir -p "$SB_HOME/bin" "$SB_HOME/messages" "$SB_HOME/documents"

install -m 0755 "$PAYLOAD_DIR/bin/sb" "$SB_HOME/bin/sb"

# Migrate the pre-0.1.31 flat layout into the style tree. Everything that
# lived in <SB_HOME>/message_definitions is ROS2-side (std/ included), so
# it moves to messages/ros2/. Runs before the payload copy so user files
# win when both exist. message_targets/ is regenerated by
# `sb message compile`, so it is dropped rather than moved.
LEGACY_DEFS="$SB_HOME/message_definitions"
LEGACY_TGTS="$SB_HOME/message_targets"
if [[ -d "$LEGACY_DEFS" ]]; then
    ROS2_DEFS="$SB_HOME/messages/ros2/message_definitions"
    mkdir -p "$ROS2_DEFS"
    moved=0
    while IFS= read -r rel; do
        rel="${rel#./}"
        # .cache/ holds the generated descriptor set — regenerated, not moved.
        case "$rel" in .cache/*) continue ;; esac
        dest="$ROS2_DEFS/$rel"
        if [[ ! -e "$dest" ]]; then
            mkdir -p "$(dirname "$dest")"
            cp "$LEGACY_DEFS/$rel" "$dest"
            moved=$((moved + 1))
        fi
    done < <(cd "$LEGACY_DEFS" && find . -type f)
    rm -rf "$LEGACY_DEFS"
    echo "  migrated: $moved file(s) message_definitions/ → messages/ros2/message_definitions/"
fi
if [[ -d "$LEGACY_TGTS" ]]; then
    rm -rf "$LEGACY_TGTS"
    echo "  migrated: dropped stale message_targets/ (regenerated by 'sb message compile')"
fi

# Message styles — never overwrite user edits.
if command -v rsync >/dev/null; then
    rsync -a --ignore-existing "$PAYLOAD_DIR/messages/" "$SB_HOME/messages/"
else
    (cd "$PAYLOAD_DIR/messages" && find . -type f) | \
    while IFS= read -r rel; do
        dest="$SB_HOME/messages/${rel#./}"
        if [[ ! -e "$dest" ]]; then
            mkdir -p "$(dirname "$dest")"
            cp "$PAYLOAD_DIR/messages/${rel#./}" "$dest"
        fi
    done
fi
echo "  messages: styles → $(cd "$SB_HOME/messages" && ls -d */ 2>/dev/null | tr -d / | tr '\n' ' ')"

# Documents — replace wholesale (reference docs ship verbatim).
rm -rf "$SB_HOME/documents"
cp -r "$PAYLOAD_DIR/documents" "$SB_HOME/documents"

cp "$PAYLOAD_DIR/VERSION" "$SB_HOME/VERSION"

# Seed config only if absent.
if [[ ! -e "$SB_HOME/sb.config.yml" && -e "$PAYLOAD_DIR/sb.config.yml.template" ]]; then
    host="$(hostname -s 2>/dev/null || hostname)"
    sed "s|__HOSTNAME__|${host}|g; s|__SB_HOME__|${SB_HOME}|g" \
        "$PAYLOAD_DIR/sb.config.yml.template" > "$SB_HOME/sb.config.yml"
    echo "  seeded $SB_HOME/sb.config.yml (device: $host)"
elif [[ -e "$SB_HOME/sb.config.yml" ]]; then
    # Migrate an existing config. `message_style`, `message_definitions`
    # and `message_targets` are DEAD as of 0.1.35: they encoded an "active
    # style" — one global mode every message name resolved against — and
    # names are fully qualified now (<style>/<namespace>/<Leaf>), so there
    # is nothing left for them to select.
    #
    # They still PARSE (an old file has to load) but do nothing, which is
    # exactly the combination that misleads. Strip them rather than leave a
    # line that reads like a live setting.
    cfg="$SB_HOME/sb.config.yml"
    tmp="$(mktemp)"
    dropped=0
    while IFS= read -r line || [[ -n "$line" ]]; do
        if [[ "$line" =~ ^[[:space:]]*message_(style|definitions|targets)[[:space:]]*: ]]; then
            dropped=$((dropped + 1))
            continue
        fi
        printf '%s\n' "$line"
    done < "$cfg" > "$tmp"

    added=0
    if ! grep -qE '^[[:space:]]*messages_root[[:space:]]*:' "$tmp"; then
        printf '\n# --- Message styles ---\n' >> "$tmp"
        printf 'messages_root: %s/messages\n' "$SB_HOME" >> "$tmp"
        added=$((added + 1))
    fi

    if (( dropped > 0 || added > 0 )); then
        cp "$cfg" "$cfg.bak"
        mv "$tmp" "$cfg"
        echo "  config: dropped $dropped dead key(s), added $added; backup at $cfg.bak"
    else
        rm -f "$tmp"
    fi
fi

# Uninstaller — shipped in the package rather than generated here, so the copy
# in $SB_HOME and the copy in the zip are the same file and cannot drift.
if [[ -f "$PAYLOAD_DIR/uninstall.sh" ]]; then
    install -m 0755 "$PAYLOAD_DIR/uninstall.sh" "$SB_HOME/uninstall.sh" 2>/dev/null \
        || { cp "$PAYLOAD_DIR/uninstall.sh" "$SB_HOME/uninstall.sh"; chmod 0755 "$SB_HOME/uninstall.sh"; }
else
    echo "  warning: no uninstall.sh in the package; $SB_HOME will have no uninstaller" >&2
fi

# Bashrc PATH wiring (only for default $HOME-based install).
RC="$HOME/.bashrc"
MARKER='# added by swarmbotix installer'
LINE="export PATH=\"\$HOME/.swarmbotix/bin:\$PATH\"  $MARKER"

if [[ "$USING_DEFAULT_HOME" -eq 0 ]]; then
    echo "Custom SB_HOME — skipping ~/.bashrc edit. Add manually:"
    echo "  export PATH=\"$SB_HOME/bin:\$PATH\""
elif [[ -f "$RC" ]] && grep -q "$MARKER" "$RC"; then
    echo "  ~/.bashrc already configured"
else
    do_edit=0
    if [[ "$YES" -eq 1 ]]; then
        do_edit=1
    elif [[ -t 0 ]]; then
        read -r -p "Add ~/.swarmbotix/bin to your PATH in ~/.bashrc? [Y/n] " ans
        case "$ans" in ""|y|Y|yes|YES) do_edit=1 ;; esac
    # `[[ -r /dev/tty ]]` is not the right test: it asks access(2), which says
    # yes even when the process has no controlling terminal to open. The open
    # then fails with ENXIO, and under `set -e` a failed redirection ends the
    # install — right at the end, with everything already copied. Attempt the
    # open instead, inside an `if` where a failure is just a false branch.
    elif { exec 3</dev/tty; } 2>/dev/null; then
        # EOF on the tty must not abort either, so tolerate a failed read and
        # treat it as "no answer" — which falls through to the manual
        # instructions below.
        read -r -p "Add ~/.swarmbotix/bin to your PATH in ~/.bashrc? [Y/n] " ans <&3 || ans=n
        exec 3<&-
        case "$ans" in ""|y|Y|yes|YES) do_edit=1 ;; esac
    fi
    if [[ "$do_edit" -eq 1 ]]; then
        printf '\n%s\n' "$LINE" >> "$RC"
        echo "  added PATH export to ~/.bashrc"
    else
        echo "Add this line to your shell config manually:"
        echo "  $LINE"
    fi
fi

# Compile every message in the vault so generated bindings (iox2 / proto / fb)
# are ready to use. Non-fatal: if protoc/flatc are missing or a message fails,
# print the error but let the install succeed — the user can re-run
# `sb message compile` after fixing the issue (`sb doctor` tells them what's
# missing).
echo
echo "Compiling message vault…"
# EVERY installed style, not just the active one. The payload ships
# definitions for all of them, and a style whose bindings were never
# generated looks broken the moment someone switches to it.
#
# Run from $SB_HOME so sb resolves the just-installed vault, not whatever
# messages/ tree happens to sit above the installer's CWD.
compile_failed=""
styles=""
if [[ -d "$SB_HOME/messages" ]]; then
    for d in "$SB_HOME"/messages/*/; do
        [[ -d "$d/message_definitions" ]] || continue
        styles="$styles $(basename "$d")"
    done
fi
if [[ -z "$styles" ]]; then
    # No style tree — one default pass.
    if ! ( cd "$SB_HOME" && SB_HOME="$SB_HOME" SB_CONFIG="$SB_HOME/sb.config.yml" \
            "$SB_HOME/bin/sb" message compile ); then
        compile_failed="(default)"
    fi
else
    for s in $styles; do
        echo "  style $s"
        if ! ( cd "$SB_HOME" && SB_HOME="$SB_HOME" SB_CONFIG="$SB_HOME/sb.config.yml" \
                "$SB_HOME/bin/sb" message compile --style "$s" ); then
            compile_failed="$compile_failed $s"
        fi
    done
fi
if [[ -z "$compile_failed" ]]; then
    echo "  message vault compiled"
else
    echo "  warning: message vault did not fully compile for:$compile_failed" >&2
    echo "           run 'sb doctor' then re-run 'sb message compile'." >&2
fi

echo
echo "Installed. Try:"
echo "  sb --version"
echo "  sb doctor"
echo
echo "To remove it later:"
echo "  $SB_HOME/uninstall.sh"
