//! frame — iceoryx2 publisher for `std/ImageStamped` on service `dev01/demo/pubber/iox2/frame`.
//!
//! Generated by `sb pub add --iox2` (L3). Re-running `sb pub edit/rm`
//! regenerates or removes this file. Hand-edits will be overwritten on
//! the next mutation.
//!
//! The iox2-flat payload type `ImageStamped` is pulled in by absolute
//! path from `/tmp/tmp.qcSpNRk8tM/message_targets/iox2/std/ImageStamped/ImageStamped.rs` — emitted by L1's `sb message
//! compile --iox2 std/ImageStamped`. Re-running that compile or moving
//! `message_targets` invalidates this file; `sb pub edit` regenerates.
//!
//! # Default wire path
//!
//! `dev01/demo/pubber/iox2/frame` — built from the per-segment defaults below. Override
//! any segment at construction time via `open_with(&node, TopicOverrides { module: Some("..".into()), ..Default::default() })`
//! for swarm-instance discrimination (e.g., a sim running N controllers).
//!
//! # Example usage
//!
//! In your project's `main.rs`:
//!
//! ```ignore
//! #[path = "swarmbotix_io/publishers/frame.rs"]
//! mod frame;
//!
//! use iceoryx2::prelude::*;
//!
//! fn main() -> Result<(), Box<dyn std::error::Error>> {
//!     let node = NodeBuilder::new().create::<ipc::Service>()?;
//!     // Plain default — uses the codegen-baked segments:
//!     let publisher = frame::FramePublisher::open(&node)?;
//!
//!     // Swarm instance — override the module segment at construction:
//!     // let id = std::env::args().nth(2).unwrap_or_default();
//!     // let ov = frame::TopicOverrides {
//!     //     module: (!id.is_empty()).then(|| format!("{}-{}", frame::DEFAULT_MODULE, id)),
//!     //     ..Default::default()
//!     // };
//!     // let publisher = frame::FramePublisher::open_with(&node, ov)?;
//!
//!     let msg = frame::ImageStamped::default();
//!     publisher.publish(msg)?;
//!     Ok(())
//! }
//! ```

use iceoryx2::prelude::*;

// iox2-flat payload type, pulled in directly from the `sb message compile
// --iox2` output tree. `#[path]` (rather than `include!()`) loads the
// file as the module's source so its `use` / attribute items resolve in
// the right scope.
#[path = "/tmp/tmp.qcSpNRk8tM/message_targets/iox2/std/ImageStamped/ImageStamped.rs"]
mod __payload;
pub use __payload::ImageStamped;

// Per-segment defaults baked at `sb pub add` time. Override any of them at
// construction (`open_with`) to vary the wire path without regenerating.
pub const DEFAULT_DEVICE: &str = "dev01";
pub const DEFAULT_WORKSPACE: &str = "demo";
pub const DEFAULT_MODULE: &str = "pubber";
pub const DEFAULT_TOPIC: &str = "frame";
pub const TRANSPORT_SEGMENT: &str = "iox2";

/// Per-segment override of the canonical wire path
/// `<device>/<workspace>/<module>/<transport>/<topic>`. `None` keeps the
/// codegen default. Set `module = Some("controller-2".into())` etc. to
/// discriminate swarm instances at runtime. Set `full = Some("...".into())`
/// to bypass the 5-segment assembly entirely and use a verbatim wire name.
#[derive(Debug, Default, Clone)]
pub struct TopicOverrides {
    pub device: Option<String>,
    pub workspace: Option<String>,
    pub module: Option<String>,
    pub topic: Option<String>,
    pub full: Option<String>,
}

impl TopicOverrides {
    /// Render the final iceoryx2 service name from this set of overrides.
    /// `full` short-circuits everything else when set.
    pub fn service_name(&self) -> String {
        if let Some(full) = &self.full {
            return full.clone();
        }
        format!(
            "{}/{}/{}/{}/{}",
            self.device.as_deref().unwrap_or(DEFAULT_DEVICE),
            self.workspace.as_deref().unwrap_or(DEFAULT_WORKSPACE),
            self.module.as_deref().unwrap_or(DEFAULT_MODULE),
            TRANSPORT_SEGMENT,
            self.topic.as_deref().unwrap_or(DEFAULT_TOPIC),
        )
    }
}

pub struct FramePublisher {
    inner: iceoryx2::port::publisher::Publisher<ipc::Service, ImageStamped, ()>,
}

impl FramePublisher {
    /// Open with all-default segments. Equivalent to
    /// `open_with(node, TopicOverrides::default())`.
    pub fn open(node: &Node<ipc::Service>) -> Result<Self, Box<dyn std::error::Error>> {
        Self::open_with(node, TopicOverrides::default())
    }

    /// Open with per-segment overrides for the wire path.
    pub fn open_with(
        node: &Node<ipc::Service>,
        overrides: TopicOverrides,
    ) -> Result<Self, Box<dyn std::error::Error>> {
        let service_name = overrides.service_name();
        let svc = ServiceName::new(&service_name)?;
        let service = node
            .service_builder(&svc)
            .publish_subscribe::<ImageStamped>()
            .open_or_create()?;
        let inner = service.publisher_builder().create()?;
        Ok(Self { inner })
    }

    /// Borrow a shared-memory slot, write `msg` into it, send it.
    /// Zero-copy from the moment `write_payload` returns.
    pub fn publish(&self, msg: ImageStamped) -> Result<(), Box<dyn std::error::Error>> {
        let sample = self.inner.loan_uninit()?;
        let sample = sample.write_payload(msg);
        sample.send()?;
        Ok(())
    }
}
