// nav_msgs/Goals.proto
//  An array of navigation goals
syntax = "proto3";

package nav_msgs;

import "geometry_msgs/PoseStamped.proto";
import "std_msgs/Header.proto";

message Goals {

  //  This header will store the time at which the poses were computed (not to be confused with the stamps of the poses themselves)
  //  In the case that individual poses do not have their frame_id set or their timetamp set they will use the default value here.
  std_msgs.Header header = 1;

  //  An array of goals to for navigation to achieve.
  //  The goals should be executed in the order of the array.
  //  The header and stamp are intended to be used for computing the position of the goals.
  //  They may vary to support cases of goals that are moving with respect to the robot.
  repeated geometry_msgs.PoseStamped goals = 2;
}
