//! Flat IR → C++ header.

use crate::ir::{FlatStruct, FlatType, GeneratedModule, ScalarTy};

pub fn emit(s: &FlatStruct) -> GeneratedModule {
    let mut buf = String::new();
    buf.push_str("// Generated by sb-iox2-typegen — DO NOT EDIT.\n");
    buf.push_str(&format!("// Source: {}/{}.proto\n", s.package, s.leaf));
    buf.push_str(
        "// Iceoryx2 zero-copy compatible: every field is fixed-size, plain old struct.\n",
    );
    buf.push_str("// Variable-length fields carry a companion `_len` / `_count` field.\n\n");

    let guard = format!(
        "SB_GEN_{}_{}_H",
        s.package.to_uppercase().replace('.', "_"),
        s.leaf.to_uppercase()
    );
    buf.push_str(&format!("#ifndef {guard}\n"));
    buf.push_str(&format!("#define {guard}\n\n"));
    buf.push_str("#include <cstdint>\n");

    // Collect repeated-struct dependencies for `#include`s.
    let mut deps: Vec<(String, String)> = Vec::new();
    for f in &s.fields {
        if let FlatType::RepeatedStruct {
            target_leaf,
            target_package,
            ..
        } = &f.ty
        {
            if (target_package.as_str(), target_leaf.as_str())
                != (s.package.as_str(), s.leaf.as_str())
            {
                deps.push((target_package.clone(), target_leaf.clone()));
            }
        }
    }
    deps.sort();
    deps.dedup();
    for (pkg, leaf) in &deps {
        buf.push_str(&format!("#include \"{pkg}/{leaf}.h\"\n"));
    }
    // C++ namespace from the proto-declared package (dots → underscores)
    // so we never collide with C++'s own `std::` namespace when the vault
    // dir happens to be `std`. File path still tracks the vault dir.
    let ns = s.package.replace('.', "_");
    buf.push_str(&format!("\nnamespace {ns} {{\n\n"));

    for d in &s.doc {
        buf.push_str(&format!("/// {d}\n"));
    }
    buf.push_str(&format!("struct {} {{\n", s.leaf));
    // Stable wire-level type identifier across language bindings; iceoryx2 looks
    // for this on the payload struct instead of the mangled C++ type name.
    buf.push_str(&format!(
        "  static constexpr const char* IOX2_TYPE_NAME = \"{}\";\n\n",
        s.leaf
    ));
    for f in &s.fields {
        for d in &f.doc {
            buf.push_str(&format!("  /// {d}\n"));
        }
        buf.push_str(&format!("  {}\n", cpp_field(&f.name, &f.ty)));
    }
    buf.push_str("};\n\n");
    buf.push_str(&format!("}}  // namespace {ns}\n\n"));
    buf.push_str(&format!("#endif  // {guard}\n"));

    GeneratedModule {
        rel_path: std::path::PathBuf::from("iox2")
            .join(s.vault_dir())
            .join(&s.leaf)
            .join(format!("{}.h", s.leaf)),
        contents: buf,
    }
}

fn cpp_field(name: &str, t: &FlatType) -> String {
    match t {
        FlatType::Scalar(s) => format!("{} {name};", cpp_scalar(*s)),
        FlatType::String { capacity } => format!("char {name}[{capacity}];"),
        FlatType::Bytes { capacity } => format!("uint8_t {name}[{capacity}];"),
        FlatType::RepeatedScalar { elem, capacity } => {
            format!("{} {name}[{capacity}];", cpp_scalar(*elem))
        }
        FlatType::RepeatedStruct {
            target_leaf,
            target_package,
            capacity,
        } => {
            // Cross-namespace ref; sanitize proto-package dots.
            let ns = target_package.replace('.', "_");
            format!(
                "::{ns}::{leaf} {name}[{cap}];",
                leaf = target_leaf,
                name = name,
                cap = capacity
            )
        }
        FlatType::RepeatedString {
            string_capacity,
            capacity,
        } => format!("char {name}[{capacity}][{string_capacity}];"),
    }
}

fn cpp_scalar(s: ScalarTy) -> &'static str {
    match s {
        ScalarTy::Bool => "bool",
        ScalarTy::I32 => "int32_t",
        ScalarTy::I64 => "int64_t",
        ScalarTy::U32 => "uint32_t",
        ScalarTy::U64 => "uint64_t",
        ScalarTy::F32 => "float",
        ScalarTy::F64 => "double",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::{FlatField, FlatStruct, FlatType, ScalarTy};

    #[test]
    fn emits_guard_namespace_and_pod_struct() {
        let s = FlatStruct {
            package: "std_msgs".into(),
            leaf: "Header".into(),
            vault_name: "std_msgs/Header".into(),
            style: "ros2".into(),
            doc: vec![],
            fields: vec![
                FlatField {
                    name: "sec".into(),
                    ty: FlatType::Scalar(ScalarTy::I32),
                    doc: vec![],
                },
                FlatField {
                    name: "frame_id".into(),
                    ty: FlatType::String { capacity: 256 },
                    doc: vec![],
                },
            ],
        };
        let g = emit(&s);
        assert!(g.contents.contains("#ifndef SB_GEN_STD_MSGS_HEADER_H"));
        assert!(g.contents.contains("namespace std_msgs {"));
        assert!(g.contents.contains("struct Header {"));
        assert!(g.contents.contains("int32_t sec;"));
        assert!(g.contents.contains("char frame_id[256];"));
        assert!(
            g.contents
                .contains("static constexpr const char* IOX2_TYPE_NAME = \"Header\";")
        );
    }
}
