//! Flat IR → C# source (iceoryx2 zero-copy compatible).
//!
//! Layout: `[StructLayout(LayoutKind.Sequential, Pack = 1)]` + `unsafe fixed`
//! buffers for primitive arrays/strings/bytes. Repeated POD structs get a
//! wrapper struct holding `N` explicitly-named fields.
//!
//! # Array wrappers live in their own files
//!
//! C# `fixed` buffers only accept primitives, so `repeated <Message>` needs a
//! generated wrapper type — the one thing here with no counterpart in the
//! Rust / C++ emitters, which have native fixed arrays.
//!
//! That wrapper is emitted by [`emit_array_wrappers`] into
//! `iox2/_arrays/<Name>.cs` under namespace [`ARRAY_NS`], **one file per
//! (element type, capacity)** — never inline in the message that uses it.
//! Inline is what shipped through 0.1.38, and it declared the same struct in
//! every message file that referenced it: two messages in one package holding
//! a `repeated Vec3Msg` produced two `swarmbotix_primitives_Vec3Msg_Array256`
//! in `namespace swarmbotix_services`, i.e. `error CS0101` (plus `CS0579` on
//! the second `[StructLayout]`, which Roslyn reports as a follow-on).
//!
//! One file per wrapper makes the filesystem enforce the dedup, which is what
//! keeps it correct under `sb message compile <one-name>`: a single-message
//! run rewrites the same path with the same bytes instead of dropping the
//! wrappers other messages need.
//!
//! # Language level: C# 9 / .NET Standard 2.1
//!
//! This emitter deliberately targets the OLDEST level any consumer uses, which
//! is Unity's. Unity auto-compiles every `.cs` under `Assets/`, and a style is
//! routinely checked out inside a Unity project, so anything newer here fails
//! the host build — one error per generated file — for code that is otherwise
//! perfectly valid.
//!
//! Two constructs were the problem and are avoided:
//!
//! - **File-scoped namespaces** (`namespace X;`) are C# 10 → `error CS8773`.
//!   Block-scoped namespaces cost one indent level and compile everywhere.
//! - **`[InlineArray(N)]`** is .NET 8 / C# 12. Replaced by a struct with `N`
//!   explicit fields under `LayoutKind.Sequential, Pack = 1`, which is the
//!   **same memory layout** — `[InlineArray]` is compact syntax, not a
//!   different representation — plus a `ref` indexer so element access reads
//!   the same at the call site.
//!
//! Nothing here is newer than C# 9, so the output stays valid on modern .NET
//! too; targeting down costs nothing and targeting up breaks Unity.

use std::collections::BTreeMap;

use crate::ir::{FlatStruct, FlatType, GeneratedModule, ScalarTy};

/// Namespace holding every generated `repeated <Message>` wrapper.
///
/// Its own namespace rather than the element's or the consumer's: these are
/// synthetic types, and a dedicated namespace can never collide with a
/// message namespace derived from a proto package.
pub const ARRAY_NS: &str = "sb_iox2_arrays";

/// Directory under the targets root holding the wrapper files. Leading
/// underscore keeps it out of the `<namespace>/<Leaf>/` message layout —
/// no proto package starts with one.
const ARRAY_DIR: &str = "_arrays";

/// `(element package, element leaf, capacity)` → wrapper struct name.
type WrapperKey = (String, String, u32);

pub fn emit(s: &FlatStruct) -> GeneratedModule {
    let mut buf = String::new();
    buf.push_str("// Generated by sb-iox2-typegen — DO NOT EDIT.\n");
    buf.push_str(&format!("// Source: {}/{}.proto\n", s.package, s.leaf));
    buf.push_str(
        "// Iceoryx2 zero-copy compatible: [StructLayout(Sequential, Pack=1)], every field fixed-size.\n",
    );
    buf.push_str("// Variable-length fields carry a companion `_len` / `_count` field.\n");
    // The language level is a contract, not trivia: this file is compiled by
    // Unity as-is whenever a style lives under Assets/, so the header states
    // what it targets and why.
    buf.push_str(
        "// Language level: C# 9 / .NET Standard 2.1 — compiles under Unity as well as\n\
         // modern .NET. Requires <AllowUnsafeBlocks>true</AllowUnsafeBlocks>.\n\n",
    );
    buf.push_str("using System.Runtime.InteropServices;\n\n");

    // Body is built unindented, then indented wholesale into the namespace
    // block below. Block-scoped rather than file-scoped: `namespace X;` is
    // C# 10 and fails Unity with CS8773.
    let mut body = String::new();
    for d in &s.doc {
        body.push_str(&format!("/// <summary>{d}</summary>\n"));
    }
    body.push_str("[StructLayout(LayoutKind.Sequential, Pack = 1)]\n");
    body.push_str(&format!("public unsafe struct {} {{\n", s.leaf));
    // Stable wire-level type identifier across language bindings; iceoryx2 reads
    // this off the payload to keep service types portable across C++/Rust/C#/Py.
    body.push_str(&format!(
        "    public const string IOX2_TYPE_NAME = \"{}\";\n\n",
        s.leaf
    ));
    for f in &s.fields {
        for d in &f.doc {
            body.push_str(&format!("    /// <summary>{d}</summary>\n"));
        }
        body.push_str(&format!("    {}\n", csharp_field(&f.name, &f.ty)));
    }
    body.push_str("}\n");

    let ns = s.package.replace('.', "_");
    buf.push_str(&format!("namespace {ns}\n{{\n"));
    for line in body.lines() {
        if line.is_empty() {
            buf.push('\n');
        } else {
            buf.push_str(&format!("    {line}\n"));
        }
    }
    buf.push_str("}\n");

    GeneratedModule {
        rel_path: std::path::PathBuf::from("iox2")
            .join(s.vault_dir())
            .join(&s.leaf)
            .join(format!("{}.cs", s.leaf)),
        contents: buf,
    }
}

/// Every `repeated <Message>` wrapper this struct references, one
/// [`GeneratedModule`] each.
///
/// Deduped by output path rather than by bookkeeping: two messages that share
/// an element type and capacity produce the same path with byte-identical
/// contents, so whichever writes second is a no-op. That property is what
/// makes a single-message `sb message compile` safe — see the module docs.
pub fn emit_array_wrappers(s: &FlatStruct) -> Vec<GeneratedModule> {
    let mut wrappers: BTreeMap<WrapperKey, ()> = BTreeMap::new();
    for f in &s.fields {
        if let FlatType::RepeatedStruct {
            target_leaf,
            target_package,
            capacity,
        } = &f.ty
        {
            wrappers.insert((target_package.clone(), target_leaf.clone(), *capacity), ());
        }
    }

    wrappers
        .keys()
        .map(|(target_pkg, target_leaf, cap)| {
            let name = wrapper_name(target_pkg, target_leaf, *cap);
            let elem = format!("global::{}.{target_leaf}", target_pkg.replace('.', "_"));

            let mut buf = String::new();
            buf.push_str("// Generated by sb-iox2-typegen — DO NOT EDIT.\n");
            buf.push_str(&format!(
                "// Fixed-capacity array of {cap} {target_pkg}.{target_leaf}.\n"
            ));
            // Say why the file exists: someone reading it wants to know why an
            // array is a struct with 256 fields, and why it isn't next to the
            // message that uses it.
            buf.push_str(
                "// Its own file because C# has no fixed-buffer syntax for struct elements:\n\
                 // the wrapper is a real type, and a type may be declared exactly once.\n",
            );
            buf.push_str(
                "// Language level: C# 9 / .NET Standard 2.1 — compiles under Unity as well as\n\
                 // modern .NET. Requires <AllowUnsafeBlocks>true</AllowUnsafeBlocks>.\n\n",
            );
            buf.push_str("using System.Runtime.InteropServices;\n\n");
            buf.push_str(&format!("namespace {ARRAY_NS}\n{{\n"));
            buf.push_str(&format!(
                "    /// <summary>Fixed-capacity array of {cap} {target_leaf}. Sequential + Pack=1\n\
                 \x20   /// gives contiguous layout without needing a .NET 8 language feature.</summary>\n"
            ));
            buf.push_str("    [StructLayout(LayoutKind.Sequential, Pack = 1)]\n");
            buf.push_str(&format!("    public unsafe struct {name} {{\n"));
            buf.push_str(&format!("        public const int Length = {cap};\n\n"));
            for i in 0..*cap {
                buf.push_str(&format!("        public {elem} _{i};\n"));
            }
            // `ref` indexer keeps call sites reading like an array despite the
            // expanded fields. Valid since C# 7; the struct is already `unsafe`.
            buf.push_str(&format!(
                "\n        /// <summary>Element access. Fields are contiguous, so this is plain\n\
                 \x20       /// pointer indexing — no bounds check, exactly like the Rust/C++ bindings.</summary>\n\
                 \x20       public ref {elem} this[int index] {{\n\
                 \x20           get {{\n\
                 \x20               fixed ({name}* self = &this) {{\n\
                 \x20                   return ref (({elem}*)self)[index];\n\
                 \x20               }}\n\
                 \x20           }}\n\
                 \x20       }}\n"
            ));
            buf.push_str("    }\n");
            buf.push_str("}\n");

            GeneratedModule {
                rel_path: std::path::PathBuf::from("iox2")
                    .join(ARRAY_DIR)
                    .join(format!("{name}.cs")),
                contents: buf,
            }
        })
        .collect()
}

/// `swarmbotix.primitives` + `Vec3Msg` + 256 → `swarmbotix_primitives_Vec3Msg_Array256`.
///
/// Fully mangled even though [`ARRAY_NS`] already separates these from
/// messages: the element package is what distinguishes two same-named leaves
/// (`std/Header` vs `std_msgs/Header`), and all wrappers share one namespace.
fn wrapper_name(target_package: &str, target_leaf: &str, capacity: u32) -> String {
    format!(
        "{}_{target_leaf}_Array{capacity}",
        target_package.replace('.', "_")
    )
}

fn csharp_field(name: &str, t: &FlatType) -> String {
    match t {
        FlatType::Scalar(s) => format!("public {} {name};", csharp_scalar(*s)),
        FlatType::String { capacity } => format!("public fixed byte {name}[{capacity}];"),
        FlatType::Bytes { capacity } => format!("public fixed byte {name}[{capacity}];"),
        FlatType::RepeatedScalar { elem, capacity } => {
            format!("public fixed {} {name}[{capacity}];", csharp_scalar(*elem))
        }
        FlatType::RepeatedStruct {
            target_leaf,
            target_package,
            capacity,
        } => {
            // Fully qualified: the wrapper lives in ARRAY_NS, never in this
            // file's namespace, and `global::` keeps it unambiguous even if a
            // message namespace ever shadows the first segment.
            format!(
                "public global::{ARRAY_NS}.{} {name};",
                wrapper_name(target_package, target_leaf, *capacity)
            )
        }
        FlatType::RepeatedString {
            string_capacity,
            capacity,
        } => {
            // 2D byte buffer flattened to 1D — C# `fixed` only supports 1D for
            // primitives, but the byte layout matches the Rust [[u8;N];M] form.
            let total = (*string_capacity as u64) * (*capacity as u64);
            format!("public fixed byte {name}[{total}]; // [{capacity}][{string_capacity}]")
        }
    }
}

fn csharp_scalar(s: ScalarTy) -> &'static str {
    match s {
        ScalarTy::Bool => "bool",
        ScalarTy::I32 => "int",
        ScalarTy::I64 => "long",
        ScalarTy::U32 => "uint",
        ScalarTy::U64 => "ulong",
        ScalarTy::F32 => "float",
        ScalarTy::F64 => "double",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::{FlatField, FlatStruct, FlatType, ScalarTy};

    #[test]
    fn emits_struct_layout_and_fixed_buffers() {
        let s = FlatStruct {
            package: "std_msgs".into(),
            leaf: "Header".into(),
            vault_name: "std_msgs/Header".into(),
            style: "ros2".into(),
            doc: vec![],
            fields: vec![
                FlatField {
                    name: "sec".into(),
                    ty: FlatType::Scalar(ScalarTy::I32),
                    doc: vec![],
                },
                FlatField {
                    name: "frame_id".into(),
                    ty: FlatType::String { capacity: 256 },
                    doc: vec![],
                },
            ],
        };
        let g = emit(&s);
        // Block-scoped, not `namespace std_msgs;` — file-scoped namespaces are
        // C# 10 and fail Unity with CS8773 once per generated file.
        assert!(
            g.contents.contains("namespace std_msgs\n{"),
            "{}",
            g.contents
        );
        assert!(!g.contents.contains("namespace std_msgs;"));
        assert!(
            g.contents
                .contains("[StructLayout(LayoutKind.Sequential, Pack = 1)]")
        );
        assert!(g.contents.contains("public unsafe struct Header {"));
        assert!(g.contents.contains("public int sec;"));
        assert!(g.contents.contains("public fixed byte frame_id[256];"));
        assert!(
            g.contents
                .contains("public const string IOX2_TYPE_NAME = \"Header\";")
        );
        assert_eq!(
            g.rel_path,
            std::path::PathBuf::from("iox2")
                .join("std_msgs")
                .join("Header")
                .join("Header.cs")
        );
    }

    fn joint_trajectory() -> FlatStruct {
        FlatStruct {
            package: "trajectory_msgs".into(),
            leaf: "JointTrajectory".into(),
            vault_name: "trajectory_msgs/JointTrajectory".into(),
            style: "ros2".into(),
            doc: vec![],
            fields: vec![FlatField {
                name: "points".into(),
                ty: FlatType::RepeatedStruct {
                    target_leaf: "JointTrajectoryPoint".into(),
                    target_package: "trajectory_msgs".into(),
                    capacity: 64,
                },
                doc: vec![],
            }],
        }
    }

    #[test]
    fn repeated_struct_field_emits_a_fixed_capacity_wrapper() {
        let w = emit_array_wrappers(&joint_trajectory());
        assert_eq!(w.len(), 1);
        let g = &w[0];
        // [InlineArray] is .NET 8 / C# 12. The wrapper expands to N explicit
        // fields under Sequential+Pack=1 instead — same bytes, C# 9 syntax.
        assert!(!g.contents.contains("InlineArray"), "{}", g.contents);
        assert!(
            !g.contents
                .contains("using System.Runtime.CompilerServices;")
        );
        assert!(
            g.contents
                .contains("public unsafe struct trajectory_msgs_JointTrajectoryPoint_Array64 {")
        );
        assert!(g.contents.contains("public const int Length = 64;"));
        assert!(
            g.contents
                .contains("public global::trajectory_msgs.JointTrajectoryPoint _0;")
        );
        assert!(
            g.contents
                .contains("public global::trajectory_msgs.JointTrajectoryPoint _63;")
        );
        assert!(
            !g.contents.contains("_64;"),
            "capacity 64 means indices 0..=63"
        );
        // The indexer is what keeps call sites identical to the [InlineArray] form.
        assert!(
            g.contents.contains(
                "public ref global::trajectory_msgs.JointTrajectoryPoint this[int index] {"
            )
        );
        assert_eq!(
            g.rel_path,
            std::path::PathBuf::from("iox2")
                .join("_arrays")
                .join("trajectory_msgs_JointTrajectoryPoint_Array64.cs")
        );
        assert!(
            g.contents.contains("namespace sb_iox2_arrays\n{"),
            "{}",
            g.contents
        );
    }

    /// The regression that shipped through 0.1.38: the wrapper was declared
    /// inline, so every message in a package that held the same
    /// `repeated <Message>` field redeclared it in that package's namespace —
    /// `CS0101`, plus `CS0579` on the second `[StructLayout]`.
    #[test]
    fn message_file_declares_no_wrapper_and_refers_to_it_qualified() {
        let g = emit(&joint_trajectory());
        assert!(
            !g.contents
                .contains("struct trajectory_msgs_JointTrajectoryPoint_Array64"),
            "the wrapper must live in its own file, not in every consumer:\n{}",
            g.contents
        );
        assert!(g.contents.contains(
            "public global::sb_iox2_arrays.trajectory_msgs_JointTrajectoryPoint_Array64 points;"
        ));
        // Nothing but the message itself is declared in the message's namespace.
        assert_eq!(
            g.contents.matches("public unsafe struct ").count(),
            1,
            "{}",
            g.contents
        );
    }

    /// Two consumers of one element type must produce the same path AND the
    /// same bytes — that is what makes writing the file twice a no-op, and
    /// what keeps a single-message compile from dropping wrappers.
    #[test]
    fn two_consumers_of_one_element_type_emit_an_identical_module() {
        let a = joint_trajectory();
        let mut b = a.clone();
        b.leaf = "OtherTrajectory".into();
        b.vault_name = "trajectory_msgs/OtherTrajectory".into();

        let wa = emit_array_wrappers(&a);
        let wb = emit_array_wrappers(&b);
        assert_eq!(wa.len(), 1);
        assert_eq!(wa[0].rel_path, wb[0].rel_path);
        assert_eq!(wa[0].contents, wb[0].contents);
    }

    /// Same element type at two capacities is two distinct types, so two files.
    #[test]
    fn distinct_capacities_get_distinct_wrappers() {
        let mut s = joint_trajectory();
        s.fields.push(FlatField {
            name: "recent".into(),
            ty: FlatType::RepeatedStruct {
                target_leaf: "JointTrajectoryPoint".into(),
                target_package: "trajectory_msgs".into(),
                capacity: 8,
            },
            doc: vec![],
        });
        let w = emit_array_wrappers(&s);
        let paths: Vec<_> = w.iter().map(|g| g.rel_path.clone()).collect();
        assert_eq!(paths.len(), 2, "{paths:?}");
        assert!(
            paths.contains(
                &std::path::PathBuf::from("iox2")
                    .join("_arrays")
                    .join("trajectory_msgs_JointTrajectoryPoint_Array64.cs")
            )
        );
        assert!(
            paths.contains(
                &std::path::PathBuf::from("iox2")
                    .join("_arrays")
                    .join("trajectory_msgs_JointTrajectoryPoint_Array8.cs")
            )
        );
    }

    /// Same leaf in two packages is two distinct element types. The package is
    /// in the wrapper name precisely so these do not collapse onto one file.
    #[test]
    fn same_leaf_in_two_packages_does_not_collide() {
        let mut s = joint_trajectory();
        s.fields.push(FlatField {
            name: "other".into(),
            ty: FlatType::RepeatedStruct {
                target_leaf: "JointTrajectoryPoint".into(),
                target_package: "other_msgs".into(),
                capacity: 64,
            },
            doc: vec![],
        });
        let w = emit_array_wrappers(&s);
        assert_eq!(w.len(), 2);
        // Order follows the BTreeMap key, so assert on the set, not on indices.
        assert!(w.iter().any(|g| {
            g.contents
                .contains("public global::other_msgs.JointTrajectoryPoint _0;")
        }));
        assert!(w.iter().any(|g| {
            g.contents
                .contains("public global::trajectory_msgs.JointTrajectoryPoint _0;")
        }));
    }

    /// Every construct newer than C# 9 that has bitten Unity, asserted absent
    /// in one place so a future emitter change cannot quietly reintroduce one.
    #[test]
    fn emitted_csharp_stays_within_csharp_9() {
        let s = FlatStruct {
            package: "swarmbotix.states".into(),
            leaf: "StatesMsg".into(),
            vault_name: "states/StatesMsg".into(),
            style: "swarmbotix".into(),
            doc: vec![],
            fields: vec![
                FlatField {
                    name: "name".into(),
                    ty: FlatType::String { capacity: 32 },
                    doc: vec![],
                },
                FlatField {
                    name: "points".into(),
                    ty: FlatType::RepeatedStruct {
                        target_leaf: "Point".into(),
                        target_package: "swarmbotix.states".into(),
                        capacity: 4,
                    },
                    doc: vec![],
                },
            ],
        };
        // Both halves of the emission: the message file and the wrapper files
        // are compiled by the same host, so both have to hold the line.
        let mut all = vec![emit(&s).contents];
        all.extend(emit_array_wrappers(&s).into_iter().map(|g| g.contents));
        // Comments are prose and may legitimately contain a forbidden keyword
        // ("its own file because …"); only the code is under test.
        let code: Vec<String> = all
            .iter()
            .map(|c| {
                c.lines()
                    .filter(|l| !l.trim_start().starts_with("//"))
                    .collect::<Vec<_>>()
                    .join("\n")
            })
            .collect();
        for c in &code {
            for forbidden in [
                "InlineArray",                  // .NET 8 / C# 12
                "namespace swarmbotix_states;", // file-scoped, C# 10 → CS8773
                "namespace sb_iox2_arrays;",    // ditto, wrapper file
                "record ",                      // C# 9 has records but not for these
                "required ",                    // C# 11
                "file ",                        // C# 11 file-local types
            ] {
                assert!(
                    !c.contains(forbidden),
                    "emitted C# must stay within C# 9, found {forbidden:?} in:\n{c}"
                );
            }
            // Namespace body must actually be indented into the block.
            assert!(c.contains("    [StructLayout(LayoutKind.Sequential, Pack = 1)]"));
            assert!(c.trim_end().ends_with('}'));
        }
        assert!(all[0].contains("namespace swarmbotix_states\n{"));
        assert!(all[1].contains("namespace sb_iox2_arrays\n{"));
    }
}
