//! Flat IR → Python ctypes.

use std::collections::BTreeSet;

use crate::ir::{FlatStruct, FlatType, GeneratedModule, ScalarTy};

pub fn emit(s: &FlatStruct) -> GeneratedModule {
    let mut buf = String::new();
    buf.push_str("# Generated by sb-iox2-typegen — DO NOT EDIT.\n");
    buf.push_str(&format!("# Source: {}/{}.proto\n", s.package, s.leaf));
    buf.push_str("# Iceoryx2 zero-copy compatible: ctypes.Structure with packed layout.\n");
    buf.push_str("# Variable-length fields carry a companion `_len` / `_count` field.\n\n");
    buf.push_str("import ctypes\n");

    // Import any repeated-struct dependencies from sibling generated modules.
    let mut deps: BTreeSet<(String, String)> = BTreeSet::new();
    for f in &s.fields {
        if let FlatType::RepeatedStruct {
            target_leaf,
            target_package,
            ..
        } = &f.ty
        {
            if (target_package.as_str(), target_leaf.as_str())
                != (s.package.as_str(), s.leaf.as_str())
            {
                deps.insert((target_package.clone(), target_leaf.clone()));
            }
        }
    }
    for (pkg, leaf) in &deps {
        // Sibling modules live at `<out>/<pkg>/<leaf>.py`. Import as
        // `from <pkg>.<leaf> import <leaf>`. Caller is expected to set
        // `__init__.py` files up so packages resolve.
        buf.push_str(&format!("from {pkg}.{leaf} import {leaf}\n"));
    }
    buf.push('\n');

    for d in &s.doc {
        buf.push_str(&format!("# {d}\n"));
    }

    buf.push_str(&format!("class {}(ctypes.Structure):\n", s.leaf));
    buf.push_str(&format!(
        "    \"\"\"{}.{} — flattened from {}/{}.proto.\"\"\"\n",
        s.package, s.leaf, s.package, s.leaf
    ));
    // Stable wire-level type identifier across language bindings; iceoryx2 reads
    // this off the payload to keep service types portable across C++/Rust/C#/Py.
    // Class attribute (not in `_fields_`) so it doesn't affect the C layout.
    buf.push_str(&format!("    IOX2_TYPE_NAME = \"{}\"\n", s.leaf));
    buf.push_str("    _pack_ = 1\n");
    buf.push_str("    _fields_ = [\n");
    for f in &s.fields {
        for d in &f.doc {
            buf.push_str(&format!("        # {d}\n"));
        }
        buf.push_str(&format!(
            "        ({:?}, {}),\n",
            f.name,
            python_type(&f.ty)
        ));
    }
    buf.push_str("    ]\n");

    GeneratedModule {
        rel_path: std::path::PathBuf::from("iox2")
            .join(s.vault_dir())
            .join(&s.leaf)
            .join(format!("{}.py", s.leaf)),
        contents: buf,
    }
}

fn python_type(t: &FlatType) -> String {
    match t {
        FlatType::Scalar(s) => python_scalar(*s).to_owned(),
        FlatType::String { capacity } => format!("ctypes.c_char * {capacity}"),
        FlatType::Bytes { capacity } => format!("ctypes.c_uint8 * {capacity}"),
        FlatType::RepeatedScalar { elem, capacity } => {
            format!("{} * {capacity}", python_scalar(*elem))
        }
        FlatType::RepeatedStruct {
            target_leaf,
            capacity,
            ..
        } => format!("{target_leaf} * {capacity}"),
        FlatType::RepeatedString {
            string_capacity,
            capacity,
        } => format!("(ctypes.c_char * {string_capacity}) * {capacity}"),
    }
}

fn python_scalar(s: ScalarTy) -> &'static str {
    match s {
        ScalarTy::Bool => "ctypes.c_bool",
        ScalarTy::I32 => "ctypes.c_int32",
        ScalarTy::I64 => "ctypes.c_int64",
        ScalarTy::U32 => "ctypes.c_uint32",
        ScalarTy::U64 => "ctypes.c_uint64",
        ScalarTy::F32 => "ctypes.c_float",
        ScalarTy::F64 => "ctypes.c_double",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::{FlatField, FlatStruct, FlatType, ScalarTy};

    #[test]
    fn emits_ctypes_structure_with_packed_layout() {
        let s = FlatStruct {
            package: "std_msgs".into(),
            leaf: "Header".into(),
            vault_name: "std_msgs/Header".into(),
            style: "ros2".into(),
            doc: vec![],
            fields: vec![
                FlatField {
                    name: "sec".into(),
                    ty: FlatType::Scalar(ScalarTy::I32),
                    doc: vec![],
                },
                FlatField {
                    name: "frame_id".into(),
                    ty: FlatType::String { capacity: 256 },
                    doc: vec![],
                },
            ],
        };
        let g = emit(&s);
        assert!(g.contents.contains("import ctypes"));
        assert!(g.contents.contains("class Header(ctypes.Structure):"));
        assert!(g.contents.contains("_pack_ = 1"));
        assert!(g.contents.contains(r#"("sec", ctypes.c_int32)"#));
        assert!(g.contents.contains(r#"("frame_id", ctypes.c_char * 256)"#));
        assert!(g.contents.contains(r#"IOX2_TYPE_NAME = "Header""#));
    }
}
