//! Flat IR → Rust source.

use crate::ir::{FlatStruct, FlatType, GeneratedModule, ScalarTy};

pub fn emit(s: &FlatStruct) -> GeneratedModule {
    let mut buf = String::new();
    buf.push_str("// Generated by sb-iox2-typegen — DO NOT EDIT.\n");
    buf.push_str(&format!(
        "// Source: {pkg}/{leaf}.proto\n",
        pkg = s.package,
        leaf = s.leaf
    ));
    buf.push_str(
        "// Iceoryx2 zero-copy compatible: every field is fixed-size, struct is #[repr(C)].\n",
    );
    buf.push_str("// Variable-length fields carry a companion `_len` / `_count` field.\n\n");

    // `use` rather than fully-qualified path in the derive — the
    // ZeroCopySend macro expansion references the trait by bare ident.
    // Required so `include!()`-style consumers (sb pub/sub codegen)
    // resolve the derive without any user wiring.
    buf.push_str("use iceoryx2::prelude::ZeroCopySend;\n\n");

    for d in &s.doc {
        buf.push_str(&format!("/// {d}\n"));
    }
    // Outer (not inner) attribute: inner attributes can't appear at the
    // start of an `include!()`-expanded body, which is the canonical way
    // sb-codegen pulls this file into a generated pub/sub module.
    buf.push_str("#[allow(non_snake_case, non_camel_case_types, dead_code)]\n");
    buf.push_str("#[repr(C)]\n");
    buf.push_str("#[derive(Debug, Clone, Copy, PartialEq, ZeroCopySend)]\n");
    // Pin the iceoryx2 wire-level type name to the proto leaf so a
    // publisher in one project and a subscriber in another agree on
    // identity. Without this iceoryx2 falls back to `type_name::<T>()`,
    // which includes the consumer crate/module path and so differs
    // between any two projects that both pull this type in.
    buf.push_str(&format!("#[type_name(\"{}\")]\n", s.leaf));
    buf.push_str(&format!("pub struct {} {{\n", s.leaf));
    for f in &s.fields {
        for d in &f.doc {
            buf.push_str(&format!("    /// {d}\n"));
        }
        buf.push_str(&format!("    pub {}: {},\n", f.name, rust_type(&f.ty)));
    }
    buf.push_str("}\n\n");

    // Stable wire-level type identifier across language bindings; iceoryx2 reads
    // this off the payload to keep service types portable across C++/Rust/C#/Py.
    buf.push_str(&format!("impl {} {{\n", s.leaf));
    buf.push_str(&format!(
        "    pub const IOX2_TYPE_NAME: &'static str = \"{}\";\n",
        s.leaf
    ));
    buf.push_str("}\n\n");

    // Default impl via zeroed (safe: all fields are POD after flattening).
    buf.push_str(&format!("impl Default for {} {{\n", s.leaf));
    buf.push_str("    fn default() -> Self {\n");
    buf.push_str("        // SAFETY: every field is POD after flattening; zeroed is valid.\n");
    buf.push_str("        unsafe { core::mem::zeroed() }\n");
    buf.push_str("    }\n");
    buf.push_str("}\n");

    GeneratedModule {
        rel_path: std::path::PathBuf::from("iox2")
            .join(s.vault_dir())
            .join(&s.leaf)
            .join(format!("{}.rs", s.leaf)),
        contents: buf,
    }
}

fn rust_type(t: &FlatType) -> String {
    match t {
        FlatType::Scalar(s) => rust_scalar(*s).to_owned(),
        FlatType::String { capacity } => format!("[u8; {capacity}]"),
        FlatType::Bytes { capacity } => format!("[u8; {capacity}]"),
        FlatType::RepeatedScalar { elem, capacity } => {
            format!("[{}; {capacity}]", rust_scalar(*elem))
        }
        FlatType::RepeatedStruct {
            target_leaf,
            capacity,
            ..
        } => format!("[{target_leaf}; {capacity}]"),
        FlatType::RepeatedString {
            string_capacity,
            capacity,
        } => format!("[[u8; {string_capacity}]; {capacity}]"),
    }
}

fn rust_scalar(s: ScalarTy) -> &'static str {
    match s {
        ScalarTy::Bool => "bool",
        ScalarTy::I32 => "i32",
        ScalarTy::I64 => "i64",
        ScalarTy::U32 => "u32",
        ScalarTy::U64 => "u64",
        ScalarTy::F32 => "f32",
        ScalarTy::F64 => "f64",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::{FlatField, FlatStruct, FlatType, ScalarTy};

    #[test]
    fn emits_repr_c_and_derives() {
        let s = FlatStruct {
            package: "std_msgs".into(),
            leaf: "Header".into(),
            vault_name: "std_msgs/Header".into(),
            style: "ros2".into(),
            doc: vec![],
            fields: vec![
                FlatField {
                    name: "sec".into(),
                    ty: FlatType::Scalar(ScalarTy::I32),
                    doc: vec![],
                },
                FlatField {
                    name: "frame_id".into(),
                    ty: FlatType::String { capacity: 256 },
                    doc: vec![],
                },
            ],
        };
        let g = emit(&s);
        assert!(g.contents.contains("#[repr(C)]"));
        assert!(g.contents.contains("pub struct Header {"));
        assert!(g.contents.contains("pub sec: i32"));
        assert!(g.contents.contains("pub frame_id: [u8; 256]"));
        assert!(g.contents.contains("use iceoryx2::prelude::ZeroCopySend;"));
        assert!(
            g.contents
                .contains("#[derive(Debug, Clone, Copy, PartialEq, ZeroCopySend)]")
        );
        assert!(
            g.contents
                .contains("pub const IOX2_TYPE_NAME: &'static str = \"Header\";")
        );
        assert_eq!(
            g.rel_path,
            std::path::PathBuf::from("iox2")
                .join("std_msgs")
                .join("Header")
                .join("Header.rs")
        );
    }
}
