// hello — Zenoh publisher for `ros2/std/StringStamped` on `/dev01/demo/pubber/zenoh/hello`.
//
// Generated by `sb pub add` (L3). Re-running `sb pub edit/rm` regenerates
// or removes this file. Hand-edits will be overwritten on the next
// mutation — keep payload encoding in your own MonoBehaviour / class.
//
// Default wire path: `dev01/demo/pubber/zenoh/hello` — built from the per-segment
// defaults below. Override at construction via the optional `device`,
// `workspace`, `module`, `topic` arguments for swarm-instance discrimination.
//
// Requires `zenoh.dll` in `Assets/Plugins/`. Unity has no iceoryx2 path.
//
// Example MonoBehaviour:
//
//   _publisher = new HelloPublisher(_session);
//   // Swarm instance:
//   //   _publisher = new HelloPublisher(_session, module: "pubber-2");

using System;
using System.Runtime.InteropServices;

namespace Swarmbotix.Io
{
    public sealed class HelloPublisher : IDisposable
    {

        public const string DefaultDevice    = "dev01";
        public const string DefaultWorkspace = "demo";
        public const string DefaultModule    = "pubber";
        public const string DefaultTopic     = "hello";
        public const string TransportSegment = "zenoh";

        public string KeyExpr { get; }

        private IntPtr _publisher;
        private bool _disposed;

        // Open against an existing Zenoh session handle. The session must
        // outlive this publisher.

        public HelloPublisher(
            IntPtr session,
            string device = null,
            string workspace = null,
            string module = null,
            string topic = null,
            string full = null)
        {
            // `full` short-circuits segment assembly when set — used verbatim.
            KeyExpr = full ?? (
                $"{device ?? DefaultDevice}/" +
                $"{workspace ?? DefaultWorkspace}/" +
                $"{module ?? DefaultModule}/" +
                $"{TransportSegment}/" +
                $"{topic ?? DefaultTopic}");
            _publisher = ZenohNative.z_declare_publisher(session, KeyExpr);
            if (_publisher == IntPtr.Zero)
                throw new InvalidOperationException("z_declare_publisher returned null for " + KeyExpr);
        }

        // Publish a serialized `ros2/std/StringStamped` payload. Encoding is the
        // caller's job — wire to protobuf-net / flatbuffers / etc.
        public void Publish(byte[] payload)
        {
            if (_disposed) throw new ObjectDisposedException(nameof(HelloPublisher));
            ZenohNative.z_publisher_put(_publisher, payload, (ulong)payload.Length);
        }

        public void Dispose()
        {
            if (_disposed) return;
            ZenohNative.z_publisher_drop(_publisher);
            _publisher = IntPtr.Zero;
            _disposed = true;
        }

        private static class ZenohNative
        {
            // Adjust the entry-point names to match your zenoh.dll build.
            [DllImport("zenohc", CallingConvention = CallingConvention.Cdecl)]
            public static extern IntPtr z_declare_publisher(IntPtr session, string keyExpr);

            [DllImport("zenohc", CallingConvention = CallingConvention.Cdecl)]
            public static extern int z_publisher_put(IntPtr publisher, byte[] payload, ulong length);

            [DllImport("zenohc", CallingConvention = CallingConvention.Cdecl)]
            public static extern void z_publisher_drop(IntPtr publisher);
        }
    }
}
