// hello — Zenoh subscriber for `ros2/std/StringStamped` on `/dev01/demo/pubber/zenoh/hello`.
//
// Generated by `sb sub add` (L3). Re-running `sb sub edit/rm` regenerates
// or removes this file. Hand-edits will be overwritten on the next
// mutation — keep payload decoding in your own MonoBehaviour / class.
//
// Default wire path: `dev01/demo/pubber/zenoh/hello` — built from the per-segment
// defaults below. Override via optional constructor args.

using System;
using System.Runtime.InteropServices;

namespace Swarmbotix.Io
{
    public sealed class HelloSubscriber : IDisposable
    {

        public const string DefaultDevice    = "dev01";
        public const string DefaultWorkspace = "demo";
        public const string DefaultModule    = "pubber";
        public const string DefaultTopic     = "hello";
        public const string TransportSegment = "zenoh";

        public string KeyExpr { get; }

        private IntPtr _subscriber;
        private byte[] _latest;
        private readonly object _gate = new object();
        private bool _disposed;


        public HelloSubscriber(
            IntPtr session,
            string device = null,
            string workspace = null,
            string module = null,
            string topic = null,
            string full = null)
        {
            // `full` short-circuits segment assembly when set — used verbatim.
            KeyExpr = full ?? (
                $"{device ?? DefaultDevice}/" +
                $"{workspace ?? DefaultWorkspace}/" +
                $"{module ?? DefaultModule}/" +
                $"{TransportSegment}/" +
                $"{topic ?? DefaultTopic}");
            var handle = GCHandle.Alloc(this);
            _subscriber = ZenohNative.z_declare_subscriber(
                session, KeyExpr, OnSample, GCHandle.ToIntPtr(handle));
            if (_subscriber == IntPtr.Zero)
            {
                handle.Free();
                throw new InvalidOperationException("z_declare_subscriber returned null for " + KeyExpr);
            }
        }

        // Return the most recent payload received since the last call,
        // or null if nothing arrived. Decoding into `ros2/std/StringStamped` is
        // the caller's job.
        public byte[] TryRecvLatest()
        {
            lock (_gate)
            {
                var out_ = _latest;
                _latest = null;
                return out_;
            }
        }

        public void Dispose()
        {
            if (_disposed) return;
            ZenohNative.z_subscriber_drop(_subscriber);
            _subscriber = IntPtr.Zero;
            _disposed = true;
        }

        [AOT.MonoPInvokeCallback(typeof(ZenohNative.SampleCallback))]
        private static void OnSample(IntPtr data, ulong len, IntPtr userCtx)
        {
            var handle = GCHandle.FromIntPtr(userCtx);
            if (!(handle.Target is HelloSubscriber self)) return;
            var buf = new byte[(int)len];
            Marshal.Copy(data, buf, 0, (int)len);
            lock (self._gate) { self._latest = buf; }
        }

        private static class ZenohNative
        {
            public delegate void SampleCallback(IntPtr data, ulong len, IntPtr userCtx);

            // Adjust the entry-point names to match your zenoh.dll build.
            [DllImport("zenohc", CallingConvention = CallingConvention.Cdecl)]
            public static extern IntPtr z_declare_subscriber(
                IntPtr session, string keyExpr, SampleCallback callback, IntPtr userCtx);

            [DllImport("zenohc", CallingConvention = CallingConvention.Cdecl)]
            public static extern void z_subscriber_drop(IntPtr subscriber);
        }
    }
}
