// hello — Zenoh publisher for `ros2/std/StringStamped` on `/dev01/demo/pubber/zenoh/hello`.
//
// Generated by `sb pub add` (L3). Re-running `sb pub edit/rm` regenerates
// or removes this file. Hand-edits will be overwritten on the next
// mutation — keep payload encoding in your own translation unit.
//
// Default wire path: `dev01/demo/pubber/zenoh/hello` — built from the per-segment
// defaults below. Override at construction via
// `HelloTopicOverrides{}` for swarm-instance discrimination.
//
// Example usage (in your project's main.cpp):
//
//   #include <zenoh.hxx>
//   #include "swarmbotix_io/publishers/hello.cpp"
//
//   int main(int argc, char** argv) {
//     auto session = zenoh::Session::open(zenoh::Config::create_default());
//     swarmbotix_io::HelloPublisher pub(session);
//     // Swarm instance:
//     //   swarmbotix_io::HelloTopicOverrides ov;
//     //   ov.module = "pubber-2";
//     //   swarmbotix_io::HelloPublisher pub(session, ov);
//
//     std::vector<uint8_t> payload = {'h','e','l','l','o'};
//     pub.publish(payload);
//     return 0;
//   }

#include <cstddef>
#include <cstdint>
#include <memory>
#include <string>
#include <string_view>
#include <vector>

#include <zenoh.hxx>

namespace swarmbotix_io {

inline constexpr std::string_view Hello_DEFAULT_DEVICE    = "dev01";
inline constexpr std::string_view Hello_DEFAULT_WORKSPACE = "demo";
inline constexpr std::string_view Hello_DEFAULT_MODULE    = "pubber";
inline constexpr std::string_view Hello_DEFAULT_TOPIC     = "hello";
inline constexpr std::string_view Hello_TRANSPORT_SEGMENT = "zenoh";

// `full` short-circuits segment assembly when set (non-empty). Like the
// per-segment fields, it is a `string_view` — the backing string must
// outlive the constructor call.
struct HelloTopicOverrides {
  std::string_view device{};
  std::string_view workspace{};
  std::string_view module{};
  std::string_view topic{};
  std::string_view full{};

  std::string key_expr() const {
    if (!full.empty()) return std::string(full);
    auto pick = [](std::string_view ov, std::string_view def) {
      return ov.empty() ? def : ov;
    };
    std::string out;
    out.reserve(64);
    out.append(pick(device,    Hello_DEFAULT_DEVICE));
    out.push_back('/');
    out.append(pick(workspace, Hello_DEFAULT_WORKSPACE));
    out.push_back('/');
    out.append(pick(module,    Hello_DEFAULT_MODULE));
    out.push_back('/');
    out.append(Hello_TRANSPORT_SEGMENT);
    out.push_back('/');
    out.append(pick(topic,     Hello_DEFAULT_TOPIC));
    return out;
  }
};

class HelloPublisher {
 public:
  // All-default constructor — equivalent to passing `HelloTopicOverrides{}`.
  explicit HelloPublisher(zenoh::Session& session)
      : HelloPublisher(session, HelloTopicOverrides{}) {}

  // Per-segment override constructor.
  HelloPublisher(zenoh::Session& session,
                    const HelloTopicOverrides& overrides)
      : key_expr_(overrides.key_expr()),
        publisher_(session.declare_publisher(zenoh::KeyExpr(key_expr_))) {}

  // Publish a serialized `ros2/std/StringStamped` payload. Encoding is the
  // caller's job — wire it to your protobuf / flatbuffers / iox2 codec.
  void publish(const std::vector<uint8_t>& payload) {
    publisher_.put(zenoh::Bytes(payload));
  }

  void publish(const void* data, std::size_t len) {
    const auto* bytes = static_cast<const uint8_t*>(data);
    publisher_.put(zenoh::Bytes(std::vector<uint8_t>(bytes, bytes + len)));
  }

  const std::string& key_expr() const { return key_expr_; }

 private:
  std::string key_expr_;
  zenoh::Publisher publisher_;
};

}  // namespace swarmbotix_io
