// image_raw — iceoryx2 publisher for `ros2/std/ImageStamped` on service `dev01/demo/pubber/iox2/image_raw`.
//
// Generated by `sb pub add --iox2` (L3). Re-running `sb pub edit/rm`
// regenerates or removes this file.
//
// The iox2-flat payload type `swarmbotix_std::ImageStamped` is
// pulled in by basename `#include "ImageStamped.h"`. L1's `sb message
// compile --iox2 ros2/std/ImageStamped` emits the header at
// `<message_targets>/iox2/std/ImageStamped/ImageStamped.h`;
// your project's build system must add an `-I` include path that points
// at that directory (canonical form:
// `-I${SB_MESSAGE_TARGETS}/iox2/std/ImageStamped`). This
// keeps the generated file portable across host and Docker builds.
//
// Default wire path: `dev01/demo/pubber/iox2/image_raw` — built from the per-segment defaults
// below. Override at construction via `ImageRawTopicOverrides{}`
// for swarm-instance discrimination.
//
// Example usage (in your project's main.cpp):
//
//   #include "iox2/iceoryx2.hpp"
//   #include "swarmbotix_io/publishers/image_raw.cpp"
//
//   int main(int argc, char** argv) {
//     auto node_exp = iox2::NodeBuilder().template create<iox2::ServiceType::Ipc>();
//     if (!node_exp.has_value()) {
//       return 1;
//     }
//     auto node = std::move(node_exp).value();
//
//     // Default: uses codegen-baked segments.
//     swarmbotix_io::ImageRawPublisher pub(node);
//
//     // Swarm instance: override the module segment at construction.
//     // swarmbotix_io::ImageRawTopicOverrides ov;
//     // ov.module = "pubber-2";
//     // swarmbotix_io::ImageRawPublisher pub(node, ov);
//
//     swarmbotix_io::ImageRaw_Payload payload{};
//     pub.publish(payload);
//     return 0;
//   }

#include <cstddef>
#include <cstdint>
#include <stdexcept>
#include <string>
#include <string_view>
#include <utility>

#include "iox2/iceoryx2.hpp"
#include "ImageStamped.h"

namespace swarmbotix_io {

namespace detail {
// `bb::Expected` (the v0.9.0 iox2 C++ binding's result type) exposes
// `has_value()`/`value()`/`error()` but no `expect()` member. This helper
// reproduces the abort-on-error semantics of Rust's `.expect("…")` by
// throwing `std::runtime_error` so the generated code stays a one-liner
// at each call site. Inline + templated so multiple translation units
// can include this header without linker collisions.
template <typename T, typename E>
inline T expect_or_throw(iox2::bb::Expected<T, E>&& exp, const char* what) {
  if (!exp.has_value()) {
    throw std::runtime_error(what);
  }
  return std::move(exp).value();
}
}  // namespace detail

using ImageRaw_Payload = swarmbotix_std::ImageStamped;

// Per-segment defaults baked at `sb pub add` time. Override at
// construction (`ImageRawTopicOverrides`) to vary the wire
// path without regenerating.
inline constexpr std::string_view ImageRaw_DEFAULT_DEVICE    = "dev01";
inline constexpr std::string_view ImageRaw_DEFAULT_WORKSPACE = "demo";
inline constexpr std::string_view ImageRaw_DEFAULT_MODULE    = "pubber";
inline constexpr std::string_view ImageRaw_DEFAULT_TOPIC     = "image_raw";
inline constexpr std::string_view ImageRaw_TRANSPORT_SEGMENT = "iox2";

// Per-segment override of the canonical wire path
// `<device>/<workspace>/<module>/<transport>/<topic>`. Empty string keeps
// the codegen default. Set `.module = "controller-2"` etc. to discriminate
// swarm instances at runtime; set `.full = "..."` to bypass segment
// assembly entirely. `full` and the per-segment fields are all
// `string_view` — the backing string must outlive the constructor.
struct ImageRawTopicOverrides {
  std::string_view device{};
  std::string_view workspace{};
  std::string_view module{};
  std::string_view topic{};
  std::string_view full{};

  std::string service_name() const {
    if (!full.empty()) return std::string(full);
    auto pick = [](std::string_view ov, std::string_view def) {
      return ov.empty() ? def : ov;
    };
    std::string out;
    out.reserve(64);
    out.append(pick(device,    ImageRaw_DEFAULT_DEVICE));
    out.push_back('/');
    out.append(pick(workspace, ImageRaw_DEFAULT_WORKSPACE));
    out.push_back('/');
    out.append(pick(module,    ImageRaw_DEFAULT_MODULE));
    out.push_back('/');
    out.append(ImageRaw_TRANSPORT_SEGMENT);
    out.push_back('/');
    out.append(pick(topic,     ImageRaw_DEFAULT_TOPIC));
    return out;
  }
};

class ImageRawPublisher {
 public:
  // All-default constructor — equivalent to passing `ImageRawTopicOverrides{}`.
  explicit ImageRawPublisher(iox2::Node<iox2::ServiceType::Ipc>& node)
      : ImageRawPublisher(node, ImageRawTopicOverrides{}) {}

  // Per-segment override constructor.
  ImageRawPublisher(iox2::Node<iox2::ServiceType::Ipc>& node,
                    const ImageRawTopicOverrides& overrides)
      : service_name_(overrides.service_name()),
        service_(detail::expect_or_throw(
            node.service_builder(detail::expect_or_throw(
                    iox2::ServiceName::create(service_name_.c_str()),
                    "ServiceName::create"))
                .template publish_subscribe<ImageRaw_Payload>()
                .open_or_create(),
            "open_or_create publish_subscribe service")),
        publisher_(detail::expect_or_throw(
            service_.publisher_builder().create(),
            "publisher_builder")) {}

  // Zero-copy publish: loan a shared-memory slot, write into it, send.
  // The const& signature is preserved by threading an rvalue copy into
  // `write_payload(T&&)` — for fixed-size iox2 payloads this is a
  // memcpy-equivalent the compiler typically elides.
  void publish(const ImageRaw_Payload& msg) {
    auto sample = detail::expect_or_throw(
        publisher_.loan_uninit(), "loan_uninit");
    auto initialized = sample.write_payload(ImageRaw_Payload(msg));
    detail::expect_or_throw(iox2::send(std::move(initialized)), "send");
  }

  const std::string& service_name() const { return service_name_; }

 private:
  std::string service_name_;
  iox2::PortFactoryPublishSubscribe<iox2::ServiceType::Ipc, ImageRaw_Payload, void> service_;
  iox2::Publisher<iox2::ServiceType::Ipc, ImageRaw_Payload, void> publisher_;
};

}  // namespace swarmbotix_io
