// hello — Zenoh subscriber for `ros2/std/StringStamped` on `/dev01/demo/pubber/zenoh/hello`.
//
// Generated by `sb sub add` (L3). Re-running `sb sub edit/rm` regenerates
// or removes this file. Hand-edits will be overwritten on the next
// mutation — keep payload decoding in your own translation unit.
//
// Default wire path: `dev01/demo/pubber/zenoh/hello` — built from the per-segment
// defaults below. Override at construction via
// `HelloTopicOverrides{}`.
//
// Example usage (in your project's main.cpp):
//
//   #include <zenoh.hxx>
//   #include "swarmbotix_io/subscribers/hello.cpp"
//
//   int main() {
//     auto session = zenoh::Session::open(zenoh::Config::create_default());
//     swarmbotix_io::HelloSubscriber sub(session);
//     while (true) {
//       if (auto bytes = sub.try_recv_latest()) {
//         std::printf("got %zu bytes\n", bytes->size());
//       }
//       std::this_thread::sleep_for(std::chrono::milliseconds(10));
//     }
//   }

#include <cstddef>
#include <cstdint>
#include <memory>
#include <mutex>
#include <optional>
#include <string>
#include <string_view>
#include <vector>

#include <zenoh.hxx>

namespace swarmbotix_io {

inline constexpr std::string_view Hello_DEFAULT_DEVICE    = "dev01";
inline constexpr std::string_view Hello_DEFAULT_WORKSPACE = "demo";
inline constexpr std::string_view Hello_DEFAULT_MODULE    = "pubber";
inline constexpr std::string_view Hello_DEFAULT_TOPIC     = "hello";
inline constexpr std::string_view Hello_TRANSPORT_SEGMENT = "zenoh";

// `full` short-circuits segment assembly when set (non-empty). Like the
// per-segment fields, it is a `string_view` — the backing string must
// outlive the constructor call.
struct HelloTopicOverrides {
  std::string_view device{};
  std::string_view workspace{};
  std::string_view module{};
  std::string_view topic{};
  std::string_view full{};

  std::string key_expr() const {
    if (!full.empty()) return std::string(full);
    auto pick = [](std::string_view ov, std::string_view def) {
      return ov.empty() ? def : ov;
    };
    std::string out;
    out.reserve(64);
    out.append(pick(device,    Hello_DEFAULT_DEVICE));
    out.push_back('/');
    out.append(pick(workspace, Hello_DEFAULT_WORKSPACE));
    out.push_back('/');
    out.append(pick(module,    Hello_DEFAULT_MODULE));
    out.push_back('/');
    out.append(Hello_TRANSPORT_SEGMENT);
    out.push_back('/');
    out.append(pick(topic,     Hello_DEFAULT_TOPIC));
    return out;
  }
};

class HelloSubscriber {
 public:
  explicit HelloSubscriber(zenoh::Session& session)
      : HelloSubscriber(session, HelloTopicOverrides{}) {}

  HelloSubscriber(zenoh::Session& session,
                    const HelloTopicOverrides& overrides)
      : key_expr_(overrides.key_expr()),
        subscriber_(session.declare_subscriber(
            zenoh::KeyExpr(key_expr_),
            [this](const zenoh::Sample& sample) {
              auto bytes = sample.get_payload().as_vector();
              std::lock_guard<std::mutex> g(mu_);
              latest_ = std::move(bytes);
            },
            zenoh::closures::none)) {}

  // Return the most recent payload (and clear the slot), or std::nullopt
  // if nothing has been received since the last call.
  std::optional<std::vector<uint8_t>> try_recv_latest() {
    std::lock_guard<std::mutex> g(mu_);
    if (!latest_) return std::nullopt;
    auto out = std::move(*latest_);
    latest_.reset();
    return out;
  }

  const std::string& key_expr() const { return key_expr_; }

 private:
  std::string key_expr_;
  std::mutex mu_;
  std::optional<std::vector<uint8_t>> latest_;
  zenoh::Subscriber<void> subscriber_;
};

}  // namespace swarmbotix_io
