// image_raw — iceoryx2 subscriber for `ros2/std/ImageStamped` on service `dev01/demo/pubber/iox2/image_raw`.
//
// Generated by `sb sub add --iox2` (L3). Re-running `sb sub edit/rm`
// regenerates or removes this file.
//
// The iox2-flat payload type `swarmbotix_std::ImageStamped` is
// pulled in by basename `#include "ImageStamped.h"`. L1's `sb message
// compile --iox2 ros2/std/ImageStamped` emits the header at
// `<message_targets>/iox2/std/ImageStamped/ImageStamped.h`;
// your project's build system must add an `-I` include path that points
// at that directory (canonical form:
// `-I${SB_MESSAGE_TARGETS}/iox2/std/ImageStamped`). This
// keeps the generated file portable across host and Docker builds.
//
// Default wire path: `dev01/demo/pubber/iox2/image_raw` — built from the per-segment defaults
// below. Override at construction via `ImageRawTopicOverrides{}`.
//
// `try_recv_latest` returns `std::optional<ImageRawSample>`,
// where `ImageRawSample` is an iceoryx2 `Sample` handle (move-only).
// **Zero-copy:** the handle aliases the publisher's shared-memory slot;
// access the payload via `.payload()` (e.g. `msg->payload().<field>`).
// Drop the optional as soon as you're done so iceoryx2 can reclaim the slot.
//
// Example usage (in your project's main.cpp):
//
//   #include "iox2/iceoryx2.hpp"
//   #include "swarmbotix_io/subscribers/image_raw.cpp"
//
//   int main() {
//     auto node_exp = iox2::NodeBuilder().template create<iox2::ServiceType::Ipc>();
//     if (!node_exp.has_value()) {
//       return 1;
//     }
//     auto node = std::move(node_exp).value();
//     swarmbotix_io::ImageRawSubscriber sub(node);
//
//     while (true) {
//       if (auto msg = sub.try_recv_latest()) {
//         // `msg->payload()` is a zero-copy reference into shared memory.
//         const auto& payload = msg->payload();
//         (void)payload;
//       }
//       std::this_thread::sleep_for(std::chrono::milliseconds(10));
//     }
//   }

#include <cstddef>
#include <cstdint>
#include <optional>
#include <stdexcept>
#include <string>
#include <string_view>
#include <utility>

#include "iox2/iceoryx2.hpp"
#include "ImageStamped.h"

namespace swarmbotix_io {

namespace detail {
// `bb::Expected` (the v0.9.0 iox2 C++ binding's result type) exposes
// `has_value()`/`value()`/`error()` but no `expect()` member. This helper
// reproduces the abort-on-error semantics of Rust's `.expect("…")` by
// throwing `std::runtime_error` so the generated code stays a one-liner
// at each call site. Inline + templated so multiple translation units
// can include this header without linker collisions.
template <typename T, typename E>
inline T expect_or_throw(iox2::bb::Expected<T, E>&& exp, const char* what) {
  if (!exp.has_value()) {
    throw std::runtime_error(what);
  }
  return std::move(exp).value();
}
}  // namespace detail

using ImageRaw_Payload = swarmbotix_std::ImageStamped;

// Zero-copy handle to a single published frame. Holding this keeps the
// shared-memory slot reserved — drop it as soon as you're done. The
// payload is reached via `sample.payload()`, returning a `const
// ImageRaw_Payload&` view of shared memory without copying.
// Move-only (Sample has a deleted copy constructor).
using ImageRawSample =
    iox2::Sample<iox2::ServiceType::Ipc, ImageRaw_Payload, void>;

inline constexpr std::string_view ImageRaw_DEFAULT_DEVICE    = "dev01";
inline constexpr std::string_view ImageRaw_DEFAULT_WORKSPACE = "demo";
inline constexpr std::string_view ImageRaw_DEFAULT_MODULE    = "pubber";
inline constexpr std::string_view ImageRaw_DEFAULT_TOPIC     = "image_raw";
inline constexpr std::string_view ImageRaw_TRANSPORT_SEGMENT = "iox2";

// `full` short-circuits segment assembly when set (non-empty). Like the
// per-segment fields, it is a `string_view` — the backing string must
// outlive the constructor call.
struct ImageRawTopicOverrides {
  std::string_view device{};
  std::string_view workspace{};
  std::string_view module{};
  std::string_view topic{};
  std::string_view full{};

  std::string service_name() const {
    if (!full.empty()) return std::string(full);
    auto pick = [](std::string_view ov, std::string_view def) {
      return ov.empty() ? def : ov;
    };
    std::string out;
    out.reserve(64);
    out.append(pick(device,    ImageRaw_DEFAULT_DEVICE));
    out.push_back('/');
    out.append(pick(workspace, ImageRaw_DEFAULT_WORKSPACE));
    out.push_back('/');
    out.append(pick(module,    ImageRaw_DEFAULT_MODULE));
    out.push_back('/');
    out.append(ImageRaw_TRANSPORT_SEGMENT);
    out.push_back('/');
    out.append(pick(topic,     ImageRaw_DEFAULT_TOPIC));
    return out;
  }
};

class ImageRawSubscriber {
 public:
  explicit ImageRawSubscriber(iox2::Node<iox2::ServiceType::Ipc>& node)
      : ImageRawSubscriber(node, ImageRawTopicOverrides{}) {}

  ImageRawSubscriber(iox2::Node<iox2::ServiceType::Ipc>& node,
                    const ImageRawTopicOverrides& overrides)
      : service_name_(overrides.service_name()),
        service_(detail::expect_or_throw(
            node.service_builder(detail::expect_or_throw(
                    iox2::ServiceName::create(service_name_.c_str()),
                    "ServiceName::create"))
                .template publish_subscribe<ImageRaw_Payload>()
                .open_or_create(),
            "open_or_create publish_subscribe service")),
        subscriber_(detail::expect_or_throw(
            service_.subscriber_builder().create(),
            "subscriber_builder")) {}

  // Drain the queue, return only the latest sample so a slow reader
  // never sees stale data. **Zero-copy:** the returned optional holds an
  // iceoryx2 `Sample` handle that aliases the publisher's shared-memory
  // slot. Access the payload via `result->payload()`; let the optional
  // go out of scope to release the slot.
  //
  // `subscriber_.receive()` returns `bb::Expected<bb::Optional<Sample>, ReceiveError>`
  // in the v0.9.0 C++ binding. The outer `Expected` is unwrapped (or thrown);
  // the inner `bb::Optional` empty state breaks the drain loop. Each
  // `emplace` destroys the previously held `Sample`, releasing that older
  // shmem slot back to the publisher before we take ownership of the next.
  std::optional<ImageRawSample> try_recv_latest() {
    std::optional<ImageRawSample> latest;
    while (true) {
      auto received = detail::expect_or_throw(
          subscriber_.receive(), "subscriber receive");
      if (!received.has_value()) {
        break;
      }
      latest.emplace(std::move(received).value());
    }
    return latest;
  }

  const std::string& service_name() const { return service_name_; }

 private:
  std::string service_name_;
  iox2::PortFactoryPublishSubscribe<iox2::ServiceType::Ipc, ImageRaw_Payload, void> service_;
  iox2::Subscriber<iox2::ServiceType::Ipc, ImageRaw_Payload, void> subscriber_;
};

}  // namespace swarmbotix_io
