// sensor_msgs/MultiEchoLaserScan.proto
//  Single scan from a multi-echo planar laser range-finder
//
//  If you have another ranging device with different behavior (e.g. a sonar
//  array), please find or create a different message, since applications
//  will make fairly laser-specific assumptions about this data
syntax = "proto3";

package sensor_msgs;

import "sensor_msgs/LaserEcho.proto";
import "std_msgs/Header.proto";

message MultiEchoLaserScan {
  std_msgs.Header header = 1;  // timestamp in the header is the acquisition time of
  //  the first ray in the scan.
  // 
  //  in frame frame_id, angles are measured around
  //  the positive Z axis (counterclockwise, if Z is up)
  //  with zero angle being forward along the x axis

  float angle_min = 2;  // start angle of the scan [rad]
  float angle_max = 3;  // end angle of the scan [rad]
  float angle_increment = 4;  // angular distance between measurements [rad]

  float time_increment = 5;  // time between measurements [seconds] - if your scanner
  //  is moving, this will be used in interpolating position
  //  of 3d points
  float scan_time = 6;  // time between scans [seconds]

  float range_min = 7;  // minimum range value [m]
  float range_max = 8;  // maximum range value [m]

  repeated sensor_msgs.LaserEcho ranges = 9;  // range data [m]
  //  (Note: NaNs, values < range_min or > range_max should be discarded)
  //  +Inf measurements are out of range
  //  -Inf measurements are too close to determine exact distance.
  repeated sensor_msgs.LaserEcho intensities = 10;  // intensity data [device-specific units].  If your
  //  device does not provide intensities, please leave
  //  the array empty.
}
