// sensor_msgs/PointField.proto
//  This message holds the description of one point entry in the
//  PointCloud2 message format.
syntax = "proto3";

package sensor_msgs;

message PointField {
  // const uint8 INT8 = 1;
  // const uint8 UINT8 = 2;
  // const uint8 INT16 = 3;
  // const uint8 UINT16 = 4;
  // const uint8 INT32 = 5;
  // const uint8 UINT32 = 6;
  // const uint8 FLOAT32 = 7;
  // const uint8 FLOAT64 = 8;
  // const uint8 INT64 = 9;
  // const uint8 UINT64 = 10;
  // const uint8 BOOL = 11;

  //  Common PointField names are x, y, z, intensity, rgb, rgba
  string name = 1;  // Name of field
  uint32 offset = 2;  // Offset from start of point struct
  uint32 datatype = 3;  // Datatype enumeration, see above
  uint32 count = 4;  // How many elements in the field
}
