// sensor_msgs/PointCloud.proto
//  THIS MESSAGE IS DEPRECATED AS OF FOXY
//  Please use sensor_msgs/PointCloud2
syntax = "proto3";

package sensor_msgs;

import "geometry_msgs/Point32.proto";
import "sensor_msgs/ChannelFloat32.proto";
import "std_msgs/Header.proto";

message PointCloud {
  //  This message holds a collection of 3d points, plus optional additional
  //  information about each point.

  //  Time of sensor data acquisition, coordinate frame ID.
  std_msgs.Header header = 1;

  //  Array of 3d points. Each Point32 should be interpreted as a 3d point
  //  in the frame given in the header.
  repeated geometry_msgs.Point32 points = 2;

  //  Each channel should have the same number of elements as points array,
  //  and the data in each channel should correspond 1:1 with each point.
  //  Channel names in common practice are listed in ChannelFloat32.msg.
  repeated sensor_msgs.ChannelFloat32 channels = 3;
}
