/// hello — Zenoh publisher for `ros2/std/StringStamped` on `/dev01/demo/pubber/zenoh/hello`.
///
/// Generated by `sb pub add` (L3). Re-running `sb pub edit/rm` regenerates
/// or removes this file. Hand-edits will be overwritten on the next
/// mutation — keep payload encoding in your own module.
///
/// Default wire path: `dev01/demo/pubber/zenoh/hello` — built from the per-segment
/// defaults below. Override at `open(...)` via named args to vary the key
/// at runtime (e.g., swarm-instance discrimination).
///
/// Requires `zenoh_flutter` in `pubspec.yaml`. Flutter has no iceoryx2
/// path — shared memory isn't available across the mobile sandbox.
///
/// Example usage (in your Flutter app's `lib/main.dart` or any class):
///
/// ```dart
/// import 'package:zenoh_flutter/zenoh_flutter.dart';
/// import 'swarmbotix_io/publishers/hello.dart';
///
/// Future<void> demo() async {
///   final session = await Zenoh.open();
///   final pub = await HelloPublisher.open(session);
///   // Swarm instance:
///   //   final pub = await HelloPublisher.open(session, module: 'pubber-2');
///   await pub.publish(Uint8List.fromList([72, 105]));
///   await pub.close();
/// }
/// ```
library;

import 'dart:typed_data';

import 'package:zenoh_flutter/zenoh_flutter.dart';

const String HelloDefaultDevice = 'dev01';
const String HelloDefaultWorkspace = 'demo';
const String HelloDefaultModule = 'pubber';
const String HelloDefaultTopic = 'hello';
const String HelloTransportSegment = 'zenoh';

String _HelloBuildKey({
  String? device,
  String? workspace,
  String? module,
  String? topic,
  String? full,
}) {
  // `full` short-circuits segment assembly when set — use verbatim.
  if (full != null) return full;
  return '${device ?? HelloDefaultDevice}/'
      '${workspace ?? HelloDefaultWorkspace}/'
      '${module ?? HelloDefaultModule}/'
      '$HelloTransportSegment/'
      '${topic ?? HelloDefaultTopic}';
}

class HelloPublisher {
  HelloPublisher._(this._publisher, this.keyExpr);

  final Publisher _publisher;
  final String keyExpr;

  /// Declare a publisher against an existing Zenoh session.
  /// Pass `device` / `workspace` / `module` / `topic` to override the
  /// codegen-baked default for that segment of the wire path.
  static Future<HelloPublisher> open(
    Session session, {
    String? device,
    String? workspace,
    String? module,
    String? topic,
    String? full,
  }) async {
    final key = _HelloBuildKey(
      device: device,
      workspace: workspace,
      module: module,
      topic: topic,
      full: full,
    );
    final pub = await session.declarePublisher(key);
    return HelloPublisher._(pub, key);
  }

  /// Publish a serialized `ros2/std/StringStamped` payload. Encoding is the
  /// caller's job — wire it to your protobuf / flatbuffers codec.
  Future<void> publish(Uint8List payload) async {
    await _publisher.put(payload);
  }

  Future<void> close() => _publisher.undeclare();
}
