/// hello — Zenoh subscriber for `ros2/std/StringStamped` on `/dev01/demo/pubber/zenoh/hello`.
///
/// Generated by `sb sub add` (L3). Re-running `sb sub edit/rm` regenerates
/// or removes this file. Hand-edits will be overwritten on the next
/// mutation — keep payload decoding in your own module.
///
/// Default wire path: `dev01/demo/pubber/zenoh/hello` — built from the per-segment
/// defaults below. Override at `open(...)` via named args.
///
/// Example usage (in your Flutter app):
///
/// ```dart
/// import 'dart:async';
/// import 'package:zenoh_flutter/zenoh_flutter.dart';
/// import 'swarmbotix_io/subscribers/hello.dart';
///
/// Future<void> demo() async {
///   final session = await Zenoh.open();
///   final sub = await HelloSubscriber.open(session);
///   Timer.periodic(const Duration(milliseconds: 50), (_) {
///     final payload = sub.tryRecvLatest();
///     if (payload != null) debugPrint('got ${payload.length} bytes');
///   });
/// }
/// ```
library;

import 'dart:typed_data';

import 'package:zenoh_flutter/zenoh_flutter.dart';

const String HelloDefaultDevice = 'dev01';
const String HelloDefaultWorkspace = 'demo';
const String HelloDefaultModule = 'pubber';
const String HelloDefaultTopic = 'hello';
const String HelloTransportSegment = 'zenoh';

String _HelloBuildKey({
  String? device,
  String? workspace,
  String? module,
  String? topic,
  String? full,
}) {
  // `full` short-circuits segment assembly when set — use verbatim.
  if (full != null) return full;
  return '${device ?? HelloDefaultDevice}/'
      '${workspace ?? HelloDefaultWorkspace}/'
      '${module ?? HelloDefaultModule}/'
      '$HelloTransportSegment/'
      '${topic ?? HelloDefaultTopic}';
}

class HelloSubscriber {
  HelloSubscriber._(this._subscriber, this.keyExpr);

  final Subscriber _subscriber;
  final String keyExpr;
  Uint8List? _latest;

  /// Declare a polling subscriber against an existing Zenoh session.
  /// Pass `device` / `workspace` / `module` / `topic` to override the
  /// codegen-baked default for that segment of the wire path.
  static Future<HelloSubscriber> open(
    Session session, {
    String? device,
    String? workspace,
    String? module,
    String? topic,
    String? full,
  }) async {
    final key = _HelloBuildKey(
      device: device,
      workspace: workspace,
      module: module,
      topic: topic,
      full: full,
    );
    late final HelloSubscriber instance;
    final sub = await session.declareSubscriber(
      key,
      (Sample sample) {
        instance._latest = Uint8List.fromList(sample.payload);
      },
    );
    instance = HelloSubscriber._(sub, key);
    return instance;
  }

  /// Return the most recent payload received since the last call, or
  /// `null` if nothing arrived. Decoding into `ros2/std/StringStamped` is the
  /// caller's job.
  Uint8List? tryRecvLatest() {
    final out = _latest;
    _latest = null;
    return out;
  }

  Future<void> close() => _subscriber.undeclare();
}
