//! hello — Zenoh publisher for `ros2/std/StringStamped` on `/dev01/demo/pubber/zenoh/hello`.
//!
//! Generated by `sb pub add` (L3). Re-running `sb pub edit/rm` regenerates
//! or removes this file. Hand-edits will be overwritten on the next
//! mutation — keep payload encoding in your own module.
//!
//! # Default wire path
//!
//! `dev01/demo/pubber/zenoh/hello` — built from the per-segment defaults below.
//! Override any segment at construction via
//! `open_with(&session, TopicOverrides { module: Some("..".into()), ..Default::default() })`
//! for swarm-instance discrimination.
//!
//! # Example usage
//!
//! ```ignore
//! #[path = "swarmbotix_io/publishers/hello.rs"]
//! mod hello;
//!
//! use zenoh::Wait;
//!
//! fn main() -> Result<(), Box<dyn std::error::Error>> {
//!     let session = zenoh::open(zenoh::Config::default()).wait()?;
//!     let publisher = hello::HelloPublisher::open(&session)?;
//!     publisher.publish(b"hello")?;
//!     Ok(())
//! }
//! ```

use zenoh::Wait;

// Per-segment defaults baked at `sb pub add` time. Override at
// construction (`open_with`) to vary the wire path without regenerating.
pub const DEFAULT_DEVICE: &str = "dev01";
pub const DEFAULT_WORKSPACE: &str = "demo";
pub const DEFAULT_MODULE: &str = "pubber";
pub const DEFAULT_TOPIC: &str = "hello";
pub const TRANSPORT_SEGMENT: &str = "zenoh";

/// Per-segment override of `<device>/<workspace>/<module>/<transport>/<topic>`.
/// `full = Some("...")` bypasses segment assembly and uses the string verbatim.
#[derive(Debug, Default, Clone)]
pub struct TopicOverrides {
    pub device: Option<String>,
    pub workspace: Option<String>,
    pub module: Option<String>,
    pub topic: Option<String>,
    pub full: Option<String>,
}

impl TopicOverrides {
    /// Render the final Zenoh key expression from this set of overrides.
    /// `full` short-circuits everything else when set.
    pub fn key_expr(&self) -> String {
        if let Some(full) = &self.full {
            return full.clone();
        }
        format!(
            "{}/{}/{}/{}/{}",
            self.device.as_deref().unwrap_or(DEFAULT_DEVICE),
            self.workspace.as_deref().unwrap_or(DEFAULT_WORKSPACE),
            self.module.as_deref().unwrap_or(DEFAULT_MODULE),
            TRANSPORT_SEGMENT,
            self.topic.as_deref().unwrap_or(DEFAULT_TOPIC),
        )
    }
}

pub struct HelloPublisher<'a> {
    publisher: zenoh::pubsub::Publisher<'a>,
}

impl<'a> HelloPublisher<'a> {
    /// Declare a publisher with all-default segments. Session must outlive
    /// the publisher (`'a`).
    pub fn open(session: &'a zenoh::Session) -> zenoh::Result<Self> {
        Self::open_with(session, TopicOverrides::default())
    }

    /// Declare a publisher with per-segment overrides.
    pub fn open_with(
        session: &'a zenoh::Session,
        overrides: TopicOverrides,
    ) -> zenoh::Result<Self> {
        let publisher = session.declare_publisher(overrides.key_expr()).wait()?;
        Ok(Self { publisher })
    }

    /// Publish a serialized `ros2/std/StringStamped` payload. Encoding is the
    /// caller's job — wire it to your prost/flatbuffers/iox2 codec of choice.
    pub fn publish(&self, payload: &[u8]) -> zenoh::Result<()> {
        self.publisher.put(payload.to_vec()).wait()?;
        Ok(())
    }
}
