//! image_raw — iceoryx2 subscriber for `ros2/std/ImageStamped` on service `dev01/demo/pubber/iox2/image_raw`.
//!
//! Generated by `sb sub add --iox2` (L3). Re-running `sb sub edit/rm`
//! regenerates or removes this file. Hand-edits will be overwritten on
//! the next mutation.
//!
//! The iox2-flat payload type `ImageStamped` is pulled in by absolute
//! path from `/sb_test_fixture/message_targets/iox2/std/ImageStamped/ImageStamped.rs` — emitted by L1's `sb message
//! compile --iox2 ros2/std/ImageStamped`. Re-running that compile or moving
//! `message_targets` invalidates this file; `sb sub edit` regenerates.
//!
//! # Default wire path
//!
//! `dev01/demo/pubber/iox2/image_raw` — built from the per-segment defaults below. Override
//! any segment at construction time via `open_with(&node, TopicOverrides { module: Some("..".into()), ..Default::default() })`
//! for swarm-instance discrimination.
//!
//! # Example usage
//!
//! `try_recv_latest` returns the iceoryx2 [`Sample`] handle directly —
//! it is **zero-copy**: holding the returned `Sample` keeps the
//! shared-memory slot reserved, and the payload is reached via deref
//! (`Sample` implements `Deref<Target = ImageStamped>`, so `msg.<field>`
//! works without an intermediate copy). Drop the sample as soon as
//! you're done so iceoryx2 can reclaim the slot for the publisher.
//!
//! In your project's `main.rs`:
//!
//! ```ignore
//! #[path = "swarmbotix_io/subscribers/image_raw.rs"]
//! mod image_raw;
//!
//! use iceoryx2::prelude::*;
//!
//! fn main() -> Result<(), Box<dyn std::error::Error>> {
//!     let node = NodeBuilder::new().create::<ipc::Service>()?;
//!     let subscriber = image_raw::ImageRawSubscriber::open(&node)?;
//!
//!     loop {
//!         if let Some(msg) = subscriber.try_recv_latest()? {
//!             // `msg` is a `Sample` aliasing shmem — no copy here.
//!             println!("{:?}", *msg);
//!         }
//!         std::thread::sleep(std::time::Duration::from_millis(10));
//!     }
//! }
//! ```

use iceoryx2::prelude::*;

// iox2-flat payload type, pulled in directly from the `sb message compile
// --iox2` output tree. `#[path]` (rather than `include!()`) loads the
// file as the module's source so its `use` / attribute items resolve in
// the right scope.
#[path = "/sb_test_fixture/message_targets/iox2/std/ImageStamped/ImageStamped.rs"]
mod __payload;
pub use __payload::ImageStamped;

// Per-segment defaults baked at `sb sub add` time. Override any of them
// at construction (`open_with`) to vary the wire path without regenerating.
pub const DEFAULT_DEVICE: &str = "dev01";
pub const DEFAULT_WORKSPACE: &str = "demo";
pub const DEFAULT_MODULE: &str = "pubber";
pub const DEFAULT_TOPIC: &str = "image_raw";
pub const TRANSPORT_SEGMENT: &str = "iox2";

/// Per-segment override of the canonical wire path
/// `<device>/<workspace>/<module>/<transport>/<topic>`. `None` keeps the
/// codegen default. Set `full = Some("...".into())` to bypass the
/// 5-segment assembly entirely and use a verbatim wire name (useful for
/// pairing with a foreign / legacy path or one computed at runtime).
#[derive(Debug, Default, Clone)]
pub struct TopicOverrides {
    pub device: Option<String>,
    pub workspace: Option<String>,
    pub module: Option<String>,
    pub topic: Option<String>,
    pub full: Option<String>,
}

impl TopicOverrides {
    pub fn service_name(&self) -> String {
        if let Some(full) = &self.full {
            return full.clone();
        }
        format!(
            "{}/{}/{}/{}/{}",
            self.device.as_deref().unwrap_or(DEFAULT_DEVICE),
            self.workspace.as_deref().unwrap_or(DEFAULT_WORKSPACE),
            self.module.as_deref().unwrap_or(DEFAULT_MODULE),
            TRANSPORT_SEGMENT,
            self.topic.as_deref().unwrap_or(DEFAULT_TOPIC),
        )
    }
}

/// Zero-copy handle to a single published frame. Holding this keeps the
/// shared-memory slot reserved — drop it as soon as you're done. The
/// payload is reached via deref: `sample.<field>` reads through to the
/// `ImageStamped` view of shared memory without copying.
pub type ImageRawSample =
    iceoryx2::sample::Sample<ipc::Service, ImageStamped, ()>;

pub struct ImageRawSubscriber {
    inner: iceoryx2::port::subscriber::Subscriber<ipc::Service, ImageStamped, ()>,
}

impl ImageRawSubscriber {
    /// Open with all-default segments.
    pub fn open(node: &Node<ipc::Service>) -> Result<Self, Box<dyn std::error::Error>> {
        Self::open_with(node, TopicOverrides::default())
    }

    /// Open with per-segment overrides for the wire path.
    pub fn open_with(
        node: &Node<ipc::Service>,
        overrides: TopicOverrides,
    ) -> Result<Self, Box<dyn std::error::Error>> {
        let service_name = overrides.service_name();
        let svc = ServiceName::new(&service_name)?;
        let service = node
            .service_builder(&svc)
            .publish_subscribe::<ImageStamped>()
            .open_or_create()?;
        let inner = service.subscriber_builder().create()?;
        Ok(Self { inner })
    }

    /// Drain the queue and return only the latest sample so a slow reader
    /// never sees stale data. **Zero-copy:** the returned [`Sample`] is a
    /// handle onto the publisher's shared-memory slot — no payload bytes
    /// are copied. Access fields via deref (`sample.<field>`). Drop the
    /// sample promptly so iceoryx2 can reclaim the slot.
    ///
    /// [`Sample`]: iceoryx2::sample::Sample
    pub fn try_recv_latest(
        &self,
    ) -> Result<Option<ImageRawSample>, Box<dyn std::error::Error>> {
        let mut latest: Option<ImageRawSample> = None;
        while let Some(sample) = self.inner.receive()? {
            // Replacing `latest` drops the previous sample, releasing
            // that older slot back to the publisher.
            latest = Some(sample);
        }
        Ok(latest)
    }
}
