//! hello — Zenoh subscriber for `ros2/std/StringStamped` on `/dev01/demo/pubber/zenoh/hello`.
//!
//! Generated by `sb sub add` (L3). Re-running `sb sub edit/rm` regenerates
//! or removes this file. Hand-edits will be overwritten on the next
//! mutation — keep payload decoding in your own module.
//!
//! # Default wire path
//!
//! `dev01/demo/pubber/zenoh/hello` — built from the per-segment defaults below.
//! Override any segment at construction via `open_with`.
//!
//! # Example usage
//!
//! ```ignore
//! #[path = "swarmbotix_io/subscribers/hello.rs"]
//! mod hello;
//!
//! use zenoh::Wait;
//!
//! fn main() -> Result<(), Box<dyn std::error::Error>> {
//!     let session = zenoh::open(zenoh::Config::default()).wait()?;
//!     let subscriber = hello::HelloSubscriber::open(&session)?;
//!
//!     loop {
//!         if let Some(bytes) = subscriber.try_recv_latest()? {
//!             println!("got {} bytes", bytes.len());
//!         }
//!         std::thread::sleep(std::time::Duration::from_millis(10));
//!     }
//! }
//! ```

use zenoh::Wait;

pub const DEFAULT_DEVICE: &str = "dev01";
pub const DEFAULT_WORKSPACE: &str = "demo";
pub const DEFAULT_MODULE: &str = "pubber";
pub const DEFAULT_TOPIC: &str = "hello";
pub const TRANSPORT_SEGMENT: &str = "zenoh";

/// Per-segment override of the Zenoh key expression. `full = Some("...")`
/// bypasses segment assembly and uses the string verbatim.
#[derive(Debug, Default, Clone)]
pub struct TopicOverrides {
    pub device: Option<String>,
    pub workspace: Option<String>,
    pub module: Option<String>,
    pub topic: Option<String>,
    pub full: Option<String>,
}

impl TopicOverrides {
    pub fn key_expr(&self) -> String {
        if let Some(full) = &self.full {
            return full.clone();
        }
        format!(
            "{}/{}/{}/{}/{}",
            self.device.as_deref().unwrap_or(DEFAULT_DEVICE),
            self.workspace.as_deref().unwrap_or(DEFAULT_WORKSPACE),
            self.module.as_deref().unwrap_or(DEFAULT_MODULE),
            TRANSPORT_SEGMENT,
            self.topic.as_deref().unwrap_or(DEFAULT_TOPIC),
        )
    }
}

pub struct HelloSubscriber {
    inner: zenoh::pubsub::Subscriber<zenoh::handlers::FifoChannelHandler<zenoh::sample::Sample>>,
}

impl HelloSubscriber {
    /// Declare a polling subscriber with all-default segments.
    pub fn open(session: &zenoh::Session) -> zenoh::Result<Self> {
        Self::open_with(session, TopicOverrides::default())
    }

    /// Declare a polling subscriber with per-segment overrides.
    pub fn open_with(
        session: &zenoh::Session,
        overrides: TopicOverrides,
    ) -> zenoh::Result<Self> {
        let inner = session.declare_subscriber(overrides.key_expr()).wait()?;
        Ok(Self { inner })
    }

    /// Drain the queue and return only the latest sample, or `Ok(None)` if
    /// nothing is queued. Decoding the bytes into `ros2/std/StringStamped` is the
    /// caller's job.
    pub fn try_recv_latest(&self) -> zenoh::Result<Option<Vec<u8>>> {
        let mut latest: Option<zenoh::sample::Sample> = None;
        loop {
            match self.inner.try_recv() {
                Ok(Some(sample)) => latest = Some(sample),
                Ok(None) => break,
                Err(e) => return Err(e.into()),
            }
        }
        Ok(latest.map(|s| s.payload().to_bytes().into_owned()))
    }
}
