"""hello — Zenoh publisher for `ros2/std/StringStamped` on `/dev01/demo/pubber/zenoh/hello`.

Generated by `sb pub add` (L3). Re-running `sb pub edit/rm` regenerates
or removes this file. Hand-edits will be overwritten on the next
mutation — keep payload encoding in your own module.

Default wire path: ``dev01/demo/pubber/zenoh/hello`` — built from the per-segment
defaults below. Override any segment via constructor kwargs to vary the
key at runtime (e.g., swarm-instance discrimination)::

    pub = HelloPublisher(session, module="controller-2")

Example usage (in your project's main.py)::

    import zenoh

    # `swarmbotix_io/` needs to be on PYTHONPATH for the bare import to
    # work — either add an `__init__.py` in it / its parents, or do:
    #
    #     import sys, pathlib
    #     sys.path.insert(0, str(pathlib.Path(__file__).parent / "swarmbotix_io"))
    #
    from publishers.hello import HelloPublisher

    # Build your `ros2/std/StringStamped` and serialize. L1's
    # `sb message compile --proto` emits `StringStamped_pb2.py` under
    # `<message_targets>/proto/std/StringStamped/`:
    #
    #     from StringStamped_pb2 import StringStamped
    #     msg = StringStamped()
    #     payload = msg.SerializeToString()
    payload = b"hello"

    with zenoh.open(zenoh.Config()) as session:
        pub = HelloPublisher(session)
        pub.publish(payload)
        pub.close()
"""

from typing import Optional

import zenoh

DEFAULT_DEVICE = "dev01"
DEFAULT_WORKSPACE = "demo"
DEFAULT_MODULE = "pubber"
DEFAULT_TOPIC = "hello"
TRANSPORT_SEGMENT = "zenoh"


class HelloPublisher:
    """Zenoh publisher wrapper. Pass an open `zenoh.Session`."""

    def __init__(
        self,
        session: zenoh.Session,
        device: Optional[str] = None,
        workspace: Optional[str] = None,
        module: Optional[str] = None,
        topic: Optional[str] = None,
        full: Optional[str] = None,
    ) -> None:
        if full is not None:
            # `full` short-circuits segment assembly — use the string verbatim.
            key = full
        else:
            key = "{}/{}/{}/{}/{}".format(
                device or DEFAULT_DEVICE,
                workspace or DEFAULT_WORKSPACE,
                module or DEFAULT_MODULE,
                TRANSPORT_SEGMENT,
                topic or DEFAULT_TOPIC,
            )
        self.key_expr = key
        self._publisher = session.declare_publisher(key)

    def publish(self, payload: bytes) -> None:
        """Publish a serialized `ros2/std/StringStamped` payload. Encoding is the
        caller's job — wire it to your protobuf / flatbuffers / iox2
        codec of choice."""
        self._publisher.put(payload)

    def close(self) -> None:
        self._publisher.undeclare()
