"""image_raw — iceoryx2 publisher for `ros2/std/ImageStamped` on service `dev01/demo/pubber/iox2/image_raw`.

Generated by `sb pub add --iox2` (L3). Re-running `sb pub edit/rm`
regenerates or removes this file. Hand-edits will be overwritten on
the next mutation — keep payload construction in your own module.

The iox2-flat payload class `ImageStamped` is loaded from the
absolute path ``/sb_test_fixture/message_targets/iox2/std/ImageStamped/ImageStamped.py`` — emitted by L1's
``sb message compile --iox2 ros2/std/ImageStamped``. Re-running that compile
or moving ``message_targets`` invalidates this file; ``sb pub edit``
regenerates.

Default wire path: ``dev01/demo/pubber/iox2/image_raw`` — built from the per-segment
defaults below. Override any segment via constructor kwargs to vary the
service name at runtime (e.g., swarm-instance discrimination)::

    pub = ImageRawPublisher(node, module="controller-2")

Wire format: a typed ``ctypes.Structure`` — iceoryx2's zero-copy contract
requires fixed-size layout.

Example usage (in your project's main.py)::

    from publishers.image_raw import ImageRawPublisher, ImageStamped, open_node

    node = open_node()
    pub = ImageRawPublisher(node)

    msg = ImageStamped()
    # msg.some_field = 42
    pub.publish(msg)
"""

import ctypes
import importlib.util as _ilu
from typing import Optional

from iceoryx2 import (
    Node,
    NodeBuilder,
    ServiceName,
    ServiceType,
)

# Load the iox2-flat payload class from its absolute on-disk path so
# users don't have to wire PYTHONPATH for it.
_spec = _ilu.spec_from_file_location("ImageStamped", r"/sb_test_fixture/message_targets/iox2/std/ImageStamped/ImageStamped.py")
if _spec is None or _spec.loader is None:
    raise ImportError(
        "could not load iox2-flat payload type for `ros2/std/ImageStamped` from "
        r"`/sb_test_fixture/message_targets/iox2/std/ImageStamped/ImageStamped.py` — run `sb message compile --iox2 ros2/std/ImageStamped` first"
    )
_mod = _ilu.module_from_spec(_spec)
_spec.loader.exec_module(_mod)
ImageStamped = _mod.ImageStamped

# Per-segment defaults baked at `sb pub add` time. Override at
# construction (kwargs) to vary the wire path without regenerating.
DEFAULT_DEVICE = "dev01"
DEFAULT_WORKSPACE = "demo"
DEFAULT_MODULE = "pubber"
DEFAULT_TOPIC = "image_raw"
TRANSPORT_SEGMENT = "iox2"


class ImageRawPublisher:
    """iceoryx2 zero-copy publisher for ``ros2/std/ImageStamped``. The payload
    class (``ImageStamped``) is hardcoded by codegen — no
    ``payload_type`` argument is needed.

    Per-segment kwargs (``device``, ``workspace``, ``module``, ``topic``)
    each default to the codegen-baked value. Override one or more to
    shift the wire path — e.g., ``module="controller-2"`` for a swarm
    instance.
    """

    def __init__(
        self,
        node: Node,
        device: Optional[str] = None,
        workspace: Optional[str] = None,
        module: Optional[str] = None,
        topic: Optional[str] = None,
        full: Optional[str] = None,
    ) -> None:
        if full is not None:
            # `full` short-circuits segment assembly — use the string verbatim.
            service_name = full
        else:
            service_name = "{}/{}/{}/{}/{}".format(
                device or DEFAULT_DEVICE,
                workspace or DEFAULT_WORKSPACE,
                module or DEFAULT_MODULE,
                TRANSPORT_SEGMENT,
                topic or DEFAULT_TOPIC,
            )
        self.service_name = service_name
        service = (
            node.service_builder(ServiceName.new(service_name))
            .publish_subscribe(ImageStamped)
            .open_or_create()
        )
        self._publisher = service.publisher_builder().create()

    def publish(self, msg: "ImageStamped") -> None:
        if not isinstance(msg, ImageStamped):
            raise TypeError(
                f"expected ImageStamped, got {type(msg).__name__}"
            )
        # Zero-copy: loan a shared-memory slot, write the struct into it,
        # send. No serialization, no allocation.
        sample = self._publisher.loan_uninit()
        initialized = sample.write_payload(msg)
        initialized.send()


def open_node() -> Node:
    """Convenience: open a fresh IPC node. Multiple publishers in the
    same process should share one Node — call this once and reuse."""
    return NodeBuilder.new().create(ServiceType.Ipc)
