"""hello — Zenoh subscriber for `ros2/std/StringStamped` on `/dev01/demo/pubber/zenoh/hello`.

Generated by `sb sub add` (L3). Re-running `sb sub edit/rm` regenerates
or removes this file. Hand-edits will be overwritten on the next
mutation — keep payload decoding in your own module.

Default wire path: ``dev01/demo/pubber/zenoh/hello`` — built from the per-segment
defaults below. Override any segment via constructor kwargs.

Example usage (in your project's main.py)::

    import time, zenoh

    # See the publisher's example for sys.path / __init__.py options.
    from subscribers.hello import HelloSubscriber

    with zenoh.open(zenoh.Config()) as session:
        sub = HelloSubscriber(session)
        while True:
            payload = sub.try_recv_latest()
            if payload is not None:
                print(f"got {len(payload)} bytes")
            time.sleep(0.01)
"""

from typing import Optional

import zenoh

DEFAULT_DEVICE = "dev01"
DEFAULT_WORKSPACE = "demo"
DEFAULT_MODULE = "pubber"
DEFAULT_TOPIC = "hello"
TRANSPORT_SEGMENT = "zenoh"


class HelloSubscriber:
    """Zenoh polling subscriber. Pass an open `zenoh.Session`."""

    def __init__(
        self,
        session: zenoh.Session,
        device: Optional[str] = None,
        workspace: Optional[str] = None,
        module: Optional[str] = None,
        topic: Optional[str] = None,
        full: Optional[str] = None,
    ) -> None:
        if full is not None:
            # `full` short-circuits segment assembly — use the string verbatim.
            key = full
        else:
            key = "{}/{}/{}/{}/{}".format(
                device or DEFAULT_DEVICE,
                workspace or DEFAULT_WORKSPACE,
                module or DEFAULT_MODULE,
                TRANSPORT_SEGMENT,
                topic or DEFAULT_TOPIC,
            )
        self.key_expr = key
        # FIFO channel handler — `try_recv` returns immediately.
        self._subscriber = session.declare_subscriber(key, zenoh.handlers.FifoChannel(64))

    def try_recv_latest(self) -> Optional[bytes]:
        """Drain the queue and return the most recent payload, or None
        if nothing is queued. Decoding the bytes into `ros2/std/StringStamped`
        is the caller's job."""
        latest: Optional[bytes] = None
        while True:
            sample = self._subscriber.try_recv()
            if sample is None:
                break
            latest = bytes(sample.payload.to_bytes())
        return latest

    def close(self) -> None:
        self._subscriber.undeclare()
