"""image_raw — iceoryx2 subscriber for `ros2/std/ImageStamped` on service `dev01/demo/pubber/iox2/image_raw`.

Generated by `sb sub add --iox2` (L3). Re-running `sb sub edit/rm`
regenerates or removes this file. Hand-edits will be overwritten on
the next mutation.

The iox2-flat payload class `ImageStamped` is loaded from the
absolute path ``/sb_test_fixture/message_targets/iox2/std/ImageStamped/ImageStamped.py`` — emitted by L1's
``sb message compile --iox2 ros2/std/ImageStamped``. Re-running that compile
or moving ``message_targets`` invalidates this file; ``sb sub edit``
regenerates.

Default wire path: ``dev01/demo/pubber/iox2/image_raw`` — built from the per-segment
defaults below. Override any segment via constructor kwargs.

Wire format: a typed ``ctypes.Structure`` from L1's ``sb message compile
--iox2``, **not** a serialized protobuf payload. Iceoryx2 is zero-copy
shared memory.

``try_recv_latest()`` returns a zero-copy view onto the publisher's
shared-memory slot. Field access on the returned object (e.g.
``msg.header_timestamp_ns``) forwards to a ``ctypes`` Structure that
aliases the slot — no payload bytes are copied. Hold the returned
object only as long as you need it; once it goes out of scope, the
iceoryx2 slot is released back to the publisher.

Example usage (in your project's main.py)::

    import time
    from subscribers.image_raw import ImageRawSubscriber, ImageStamped, open_node

    node = open_node()
    sub = ImageRawSubscriber(node)

    while True:
        msg = sub.try_recv_latest()
        if msg is not None:
            # `msg.<field>` reads through to the shmem-backed payload
            # without copying. Use `msg._view` for the raw ctypes
            # Structure (e.g. `ctypes.addressof(msg._view)`).
            pass
        time.sleep(0.01)
"""

import importlib.util as _ilu
from typing import Optional

from iceoryx2 import (
    Node,
    NodeBuilder,
    ServiceName,
    ServiceType,
)

# Load the iox2-flat payload class from its absolute on-disk path so
# users don't have to wire PYTHONPATH for it.
_spec = _ilu.spec_from_file_location("ImageStamped", r"/sb_test_fixture/message_targets/iox2/std/ImageStamped/ImageStamped.py")
if _spec is None or _spec.loader is None:
    raise ImportError(
        "could not load iox2-flat payload type for `ros2/std/ImageStamped` from "
        r"`/sb_test_fixture/message_targets/iox2/std/ImageStamped/ImageStamped.py` — run `sb message compile --iox2 ros2/std/ImageStamped` first"
    )
_mod = _ilu.module_from_spec(_spec)
_spec.loader.exec_module(_mod)
ImageStamped = _mod.ImageStamped

DEFAULT_DEVICE = "dev01"
DEFAULT_WORKSPACE = "demo"
DEFAULT_MODULE = "pubber"
DEFAULT_TOPIC = "image_raw"
TRANSPORT_SEGMENT = "iox2"


class ImageRawSample:
    """Zero-copy view of one iceoryx2 sample. Field access (e.g.
    ``view.header_timestamp_ns``) forwards to a ``ctypes`` Structure
    backed directly by shared memory — no payload bytes are copied. The
    shared-memory slot stays reserved while this view is alive, so let
    it drop as soon as you're done reading.

    The raw ctypes Structure is available as ``view._view`` if you need
    to pass it to ``ctypes.addressof``, ``memoryview``, ``ctypes.string_at``,
    etc. (No public ``payload`` accessor — that would shadow proto fields
    named ``payload``.)"""

    __slots__ = ("_sample", "_view")

    def __init__(self, sample: object) -> None:
        # The Sample handle keeps the iceoryx2 slot alive; the ctypes
        # Structure obtained from `payload().contents` aliases that
        # slot without copying. Both references must outlive any field
        # read, which is why the wrapper holds onto them together.
        self._sample = sample
        self._view = sample.payload().contents

    def __getattr__(self, name: str):
        # Only called when normal attribute lookup (slots) misses, so
        # reads of payload fields land here and forward straight
        # through to the shmem-backed Structure.
        return getattr(self._view, name)


class ImageRawSubscriber:
    """iceoryx2 polling subscriber for ``ros2/std/ImageStamped``. The payload
    class (``ImageStamped``) is hardcoded by codegen — no
    ``payload_type`` argument is needed."""

    def __init__(
        self,
        node: Node,
        device: Optional[str] = None,
        workspace: Optional[str] = None,
        module: Optional[str] = None,
        topic: Optional[str] = None,
        full: Optional[str] = None,
    ) -> None:
        if full is not None:
            # `full` short-circuits segment assembly — use the string verbatim.
            service_name = full
        else:
            service_name = "{}/{}/{}/{}/{}".format(
                device or DEFAULT_DEVICE,
                workspace or DEFAULT_WORKSPACE,
                module or DEFAULT_MODULE,
                TRANSPORT_SEGMENT,
                topic or DEFAULT_TOPIC,
            )
        self.service_name = service_name
        service = (
            node.service_builder(ServiceName.new(service_name))
            .publish_subscribe(ImageStamped)
            .open_or_create()
        )
        self._subscriber = service.subscriber_builder().create()

    def try_recv_latest(self) -> "Optional[ImageRawSample]":
        """Drain the queue and return only the most recent sample, or
        ``None`` if nothing is queued.

        **Zero-copy:** the returned :class:`ImageRawSample`
        forwards field reads to a ``ctypes`` Structure backed by the
        publisher's shared-memory slot. Holding the returned object
        keeps the slot reserved; drop it as soon as you've read what
        you need."""
        latest = None
        while True:
            sample = self._subscriber.receive()
            if sample is None:
                break
            # Re-binding `latest` drops the previous Sample (if any),
            # which releases that older slot back to the publisher.
            latest = sample
        if latest is None:
            return None
        return ImageRawSample(latest)


def open_node() -> Node:
    """Convenience: open a fresh IPC node. Multiple subscribers in the
    same process should share one Node — call this once and reuse."""
    return NodeBuilder.new().create(ServiceType.Ipc)
