// shape_msgs/SolidPrimitive.proto
//  Defines box, sphere, cylinder, cone and prism.
//  All shapes are defined to have their bounding boxes centered around 0,0,0.
syntax = "proto3";

package shape_msgs;

import "geometry_msgs/Polygon.proto";

message SolidPrimitive {
  // const uint8 BOX = 1;
  // const uint8 SPHERE = 2;
  // const uint8 CYLINDER = 3;
  // const uint8 CONE = 4;
  // const uint8 PRISM = 5;

  //  The type of the shape
  uint32 type = 1;

  //  The dimensions of the shape
  repeated double dimensions = 2;  // bounded <=3 | At no point will dimensions have a length > 3.

  //  The meaning of the shape dimensions: each constant defines the index in the 'dimensions' array.

  //  For type BOX, the X, Y, and Z dimensions are the length of the corresponding sides of the box.
  // const uint8 BOX_X = 0;
  // const uint8 BOX_Y = 1;
  // const uint8 BOX_Z = 2;

  //  For the SPHERE type, only one component is used, and it gives the radius of the sphere.
  // const uint8 SPHERE_RADIUS = 0;

  //  For the CYLINDER and CONE types, the center line is oriented along the Z axis.
  //  Therefore the CYLINDER_HEIGHT (CONE_HEIGHT) component of dimensions gives the
  //  height of the cylinder (cone).
  //  The CYLINDER_RADIUS (CONE_RADIUS) component of dimensions gives the radius of
  //  the base of the cylinder (cone).
  //  Cone and cylinder primitives are defined to be circular. The tip of the cone
  //  is pointing up, along +Z axis.

  // const uint8 CYLINDER_HEIGHT = 0;
  // const uint8 CYLINDER_RADIUS = 1;

  // const uint8 CONE_HEIGHT = 0;
  // const uint8 CONE_RADIUS = 1;

  //  For the type PRISM, the center line is oriented along Z axis.
  //  The PRISM_HEIGHT component of dimensions gives the
  //  height of the prism.
  //  The polygon defines the Z axis centered base of the prism.
  //  The prism is constructed by extruding the base in +Z and -Z
  //  directions by half of the PRISM_HEIGHT
  //  Only x and y fields of the points are used in the polygon.
  //  Points of the polygon are ordered counter-clockwise.

  // const uint8 PRISM_HEIGHT = 0;
  geometry_msgs.Polygon polygon = 3;
}
