//! hello — Zenoh publisher for `std/StringStamped` on `/dev01/demo/pubber/hello`.
//!
//! Generated by `sb pub add` (L3). Re-running `sb pub edit/rm` regenerates
//! or removes this file. Hand-edits will be overwritten on the next
//! mutation — keep payload encoding in your own module.
//!
//! # Example usage
//!
//! In your project's `main.rs` (or `lib.rs`):
//!
//! ```ignore
//! // Mount the generated file as a module. `#[path]` lets you keep your
//! // own crate layout; the default emits to `swarmbotix_io/publishers/`.
//! #[path = "swarmbotix_io/publishers/hello.rs"]
//! mod hello;
//!
//! use zenoh::Wait;
//!
//! fn main() -> Result<(), Box<dyn std::error::Error>> {
//!     let session = zenoh::open(zenoh::Config::default()).wait()?;
//!     let publisher = hello::HelloPublisher::open(&session)?;
//!
//!     // Build a `std/StringStamped` and serialize it to bytes. Use the
//!     // prost-generated type from L1's `sb message compile --proto`
//!     // (lands under <message_targets>/proto/std/StringStamped/).
//!     // Example with prost:
//!     //
//!     //   use prost::Message;
//!     //   let msg = StringStamped { /* fields */ ..Default::default() };
//!     //   let mut buf = Vec::new();
//!     //   msg.encode(&mut buf)?;
//!     //   publisher.publish(&buf)?;
//!     //
//!     // For a quick smoke test, just push raw bytes:
//!     publisher.publish(b"hello")?;
//!     Ok(())
//! }
//! ```

use zenoh::Wait;

pub const TOPIC: &str = "dev01/demo/pubber/hello";

pub struct HelloPublisher<'a> {
    publisher: zenoh::pubsub::Publisher<'a>,
}

impl<'a> HelloPublisher<'a> {
    /// Declare the publisher against an existing Zenoh session. The session
    /// must outlive the publisher (`'a`).
    pub fn open(session: &'a zenoh::Session) -> zenoh::Result<Self> {
        let publisher = session.declare_publisher(TOPIC).wait()?;
        Ok(Self { publisher })
    }

    /// Publish a serialized `std/StringStamped` payload. Encoding is the
    /// caller's job — wire it to your prost/flatbuffers/iox2 codec of choice.
    pub fn publish(&self, payload: &[u8]) -> zenoh::Result<()> {
        self.publisher.put(payload.to_vec()).wait()?;
        Ok(())
    }
}
