//! frame — iceoryx2 subscriber for `std/ImageStamped` on service `dev01/demo/pubber/iox2/frame`.
//!
//! Generated by `sb sub add --iox2` (L3). Re-running `sb sub edit/rm`
//! regenerates or removes this file. Hand-edits will be overwritten on
//! the next mutation.
//!
//! The iox2-flat payload type `ImageStamped` is pulled in by absolute
//! path from `/tmp/tmp.qcSpNRk8tM/message_targets/iox2/std/ImageStamped/ImageStamped.rs` — emitted by L1's `sb message
//! compile --iox2 std/ImageStamped`. Re-running that compile or moving
//! `message_targets` invalidates this file; `sb sub edit` regenerates.
//!
//! # Default wire path
//!
//! `dev01/demo/pubber/iox2/frame` — built from the per-segment defaults below. Override
//! any segment at construction time via `open_with(&node, TopicOverrides { module: Some("..".into()), ..Default::default() })`
//! for swarm-instance discrimination.
//!
//! # Example usage
//!
//! `try_recv_latest` returns the iceoryx2 [`Sample`] handle directly —
//! it is **zero-copy**: holding the returned `Sample` keeps the
//! shared-memory slot reserved, and the payload is reached via deref
//! (`Sample` implements `Deref<Target = ImageStamped>`, so `msg.<field>`
//! works without an intermediate copy). Drop the sample as soon as
//! you're done so iceoryx2 can reclaim the slot for the publisher.
//!
//! In your project's `main.rs`:
//!
//! ```ignore
//! #[path = "swarmbotix_io/subscribers/frame.rs"]
//! mod frame;
//!
//! use iceoryx2::prelude::*;
//!
//! fn main() -> Result<(), Box<dyn std::error::Error>> {
//!     let node = NodeBuilder::new().create::<ipc::Service>()?;
//!     let subscriber = frame::FrameSubscriber::open(&node)?;
//!
//!     loop {
//!         if let Some(msg) = subscriber.try_recv_latest()? {
//!             // `msg` is a `Sample` aliasing shmem — no copy here.
//!             println!("{:?}", *msg);
//!         }
//!         std::thread::sleep(std::time::Duration::from_millis(10));
//!     }
//! }
//! ```

use iceoryx2::prelude::*;

// iox2-flat payload type, pulled in directly from the `sb message compile
// --iox2` output tree. `#[path]` (rather than `include!()`) loads the
// file as the module's source so its `use` / attribute items resolve in
// the right scope.
#[path = "/tmp/tmp.qcSpNRk8tM/message_targets/iox2/std/ImageStamped/ImageStamped.rs"]
mod __payload;
pub use __payload::ImageStamped;

// Foreign topic — the user passed a leading-slash path verbatim, so the
// wire form is fixed and per-segment overrides don't apply. Use `open()`.
pub const SERVICE: &str = "dev01/demo/pubber/iox2/frame";

/// Zero-copy handle to a single published frame. Holding this keeps the
/// shared-memory slot reserved — drop it as soon as you're done. The
/// payload is reached via deref: `sample.<field>` reads through to the
/// `ImageStamped` view of shared memory without copying.
pub type FrameSample =
    iceoryx2::sample::Sample<ipc::Service, ImageStamped, ()>;

pub struct FrameSubscriber {
    inner: iceoryx2::port::subscriber::Subscriber<ipc::Service, ImageStamped, ()>,
}

impl FrameSubscriber {
    pub fn open(
        node: &Node<ipc::Service>,
    ) -> Result<Self, Box<dyn std::error::Error>> {
        let svc = ServiceName::new(SERVICE)?;
        let service = node
            .service_builder(&svc)
            .publish_subscribe::<ImageStamped>()
            .open_or_create()?;
        let inner = service.subscriber_builder().create()?;
        Ok(Self { inner })
    }

    /// Drain the queue and return only the latest sample so a slow reader
    /// never sees stale data. **Zero-copy:** the returned [`Sample`] is a
    /// handle onto the publisher's shared-memory slot — no payload bytes
    /// are copied. Access fields via deref (`sample.<field>`). Drop the
    /// sample promptly so iceoryx2 can reclaim the slot.
    ///
    /// [`Sample`]: iceoryx2::sample::Sample
    pub fn try_recv_latest(
        &self,
    ) -> Result<Option<FrameSample>, Box<dyn std::error::Error>> {
        let mut latest: Option<FrameSample> = None;
        while let Some(sample) = self.inner.receive()? {
            // Replacing `latest` drops the previous sample, releasing
            // that older slot back to the publisher.
            latest = Some(sample);
        }
        Ok(latest)
    }
}
