//! hello — Zenoh subscriber for `std/StringStamped` on `/dev01/demo/pubber/hello`.
//!
//! Generated by `sb sub add` (L3). Re-running `sb sub edit/rm` regenerates
//! or removes this file. Hand-edits will be overwritten on the next
//! mutation — keep payload decoding in your own module.
//!
//! # Example usage
//!
//! In your project's `main.rs`:
//!
//! ```ignore
//! #[path = "swarmbotix_io/subscribers/hello.rs"]
//! mod hello;
//!
//! use zenoh::Wait;
//!
//! fn main() -> Result<(), Box<dyn std::error::Error>> {
//!     let session = zenoh::open(zenoh::Config::default()).wait()?;
//!     let subscriber = hello::HelloSubscriber::open(&session)?;
//!
//!     loop {
//!         if let Some(bytes) = subscriber.try_recv_latest()? {
//!             // Decode `std/StringStamped` from the bytes. Example with prost:
//!             //
//!             //   use prost::Message;
//!             //   let msg = StringStamped::decode(bytes.as_slice())?;
//!             //   println!("{:?}", msg);
//!             println!("got {} bytes", bytes.len());
//!         }
//!         std::thread::sleep(std::time::Duration::from_millis(10));
//!     }
//! }
//! ```

use zenoh::Wait;

pub const TOPIC: &str = "dev01/demo/pubber/hello";

pub struct HelloSubscriber {
    inner: zenoh::pubsub::Subscriber<zenoh::handlers::FifoChannelHandler<zenoh::sample::Sample>>,
}

impl HelloSubscriber {
    /// Declare a polling subscriber. The Zenoh subscriber owns its session
    /// reference internally, so the returned value has no lifetime parameter.
    pub fn open(session: &zenoh::Session) -> zenoh::Result<Self> {
        let inner = session.declare_subscriber(TOPIC).wait()?;
        Ok(Self { inner })
    }

    /// Drain the queue and return only the latest sample, or `Ok(None)` if
    /// nothing is queued. Decoding the bytes into `std/StringStamped` is the
    /// caller's job.
    pub fn try_recv_latest(&self) -> zenoh::Result<Option<Vec<u8>>> {
        let mut latest: Option<zenoh::sample::Sample> = None;
        loop {
            match self.inner.try_recv() {
                Ok(Some(sample)) => latest = Some(sample),
                Ok(None) => break,
                Err(e) => return Err(e.into()),
            }
        }
        Ok(latest.map(|s| s.payload().to_bytes().into_owned()))
    }
}
