"""hello — Zenoh subscriber for `std/StringStamped` on `/dev01/demo/pubber_rust/hello`.

Generated by `sb sub add` (L3). Re-running `sb sub edit/rm` regenerates
or removes this file. Hand-edits will be overwritten on the next
mutation — keep payload decoding in your own module.

Example usage (in your project's main.py)::

    import time
    import zenoh

    # See the publisher's example for sys.path / __init__.py options.
    from subscribers.hello import HelloSubscriber

    with zenoh.open(zenoh.Config()) as session:
        sub = HelloSubscriber(session)
        while True:
            payload = sub.try_recv_latest()
            if payload is not None:
                # Decode `std/StringStamped` from `payload`. L1 emits
                # `StringStamped_pb2.py` under <message_targets>/proto/
                # std/StringStamped/:
                #
                #     from StringStamped_pb2 import StringStamped
                #     msg = StringStamped()
                #     msg.ParseFromString(payload)
                #     print(msg)
                print(f"got {len(payload)} bytes")
            time.sleep(0.01)
"""

from typing import Optional

import zenoh

TOPIC = "dev01/demo/pubber_rust/hello"


class HelloSubscriber:
    """Zenoh polling subscriber. Pass an open `zenoh.Session`."""

    def __init__(self, session: zenoh.Session) -> None:
        # FIFO channel handler — `try_recv` returns immediately.
        self._subscriber = session.declare_subscriber(TOPIC, zenoh.handlers.FifoChannel(64))

    def try_recv_latest(self) -> Optional[bytes]:
        """Drain the queue and return the most recent payload, or None
        if nothing is queued. Decoding the bytes into `std/StringStamped`
        is the caller's job."""
        latest: Optional[bytes] = None
        while True:
            sample = self._subscriber.try_recv()
            if sample is None:
                break
            latest = bytes(sample.payload.to_bytes())
        return latest

    def close(self) -> None:
        self._subscriber.undeclare()
